// Beispielsätze — Kontext zu einzelnen Einträgen.
//
// WICHTIG: Diese Sätze stammen NICHT aus dem Kursbuch. Sie sind auf A2-Niveau
// selbst formuliert. Für Klausurzitate taugen sie nicht — die Vokabeln selbst
// kommen aus dem Glossar (siehe vocab.js), die Sätze drumherum nicht.
//
// Schlüssel = spanisches Wort aus vocab.js ODER Verbschlüssel aus app.js
// (verb:<infinitiv>:<zeit>, special:<infinitiv>).
// Jeder Satz MUSS das Zielwort wörtlich enthalten — sonst lässt sich daraus
// keine Lücke bilden (siehe Lückentext-Modus).

const SENTENCES = {
  // ============ Verben: alle Zeitformen ============
  "verb:hablar:Presente":     { es: "Yo hablo español con mis amigos.", de: "Ich spreche Spanisch mit meinen Freunden." },
  "verb:hablar:Indefinido":   { es: "Ayer hablé con mi profesora.", de: "Gestern sprach ich mit meiner Lehrerin." },
  "verb:hablar:Perfecto":     { es: "Hoy he hablado con mi madre.", de: "Heute habe ich mit meiner Mutter gesprochen." },
  "verb:hablar:Condicional":  { es: "Yo hablaría más si tuviera tiempo.", de: "Ich würde mehr sprechen, wenn ich Zeit hätte." },

  "verb:comer:Presente":      { es: "Nosotros comemos a las dos.", de: "Wir essen um zwei." },
  "verb:comer:Indefinido":    { es: "Anoche comí en un restaurante.", de: "Gestern Abend aß ich in einem Restaurant." },
  "verb:comer:Perfecto":      { es: "Ya he comido, gracias.", de: "Ich habe schon gegessen, danke." },
  "verb:comer:Condicional":   { es: "Yo comería menos azúcar.", de: "Ich würde weniger Zucker essen." },

  "verb:vivir:Presente":      { es: "Ella vive en Madrid desde enero.", de: "Sie wohnt seit Januar in Madrid." },
  "verb:vivir:Indefinido":    { es: "Viví dos años en Alemania.", de: "Ich lebte zwei Jahre in Deutschland." },
  "verb:vivir:Perfecto":      { es: "Siempre he vivido en el campo.", de: "Ich habe immer auf dem Land gelebt." },
  "verb:vivir:Condicional":   { es: "Yo viviría cerca del mar.", de: "Ich würde gern in der Nähe des Meeres wohnen." },

  "verb:ser:Presente":        { es: "Mi hermana es muy simpática.", de: "Meine Schwester ist sehr sympathisch." },
  "verb:ser:Indefinido":      { es: "La fiesta fue un éxito.", de: "Das Fest war ein Erfolg." },
  "verb:ser:Perfecto":        { es: "Este año ha sido difícil.", de: "Dieses Jahr ist schwierig gewesen." },
  "verb:ser:Condicional":     { es: "Sería mejor salir temprano.", de: "Es wäre besser, früh loszugehen." },

  "verb:estar:Presente":      { es: "El libro está en la mesa.", de: "Das Buch liegt auf dem Tisch." },
  "verb:estar:Indefinido":    { es: "Ayer estuve en el museo.", de: "Gestern war ich im Museum." },
  "verb:estar:Perfecto":      { es: "Hoy he estado muy cansado.", de: "Heute bin ich sehr müde gewesen." },
  "verb:estar:Condicional":   { es: "Estaría mejor con un café.", de: "Mit einem Kaffee ginge es mir besser." },

  "verb:tener:Presente":      { es: "Tengo dos hermanos mayores.", de: "Ich habe zwei ältere Brüder." },
  "verb:tener:Indefinido":    { es: "Tuve mucha suerte en el examen.", de: "Ich hatte viel Glück bei der Prüfung." },
  "verb:tener:Perfecto":      { es: "Nunca he tenido un coche.", de: "Ich habe nie ein Auto gehabt." },
  "verb:tener:Condicional":   { es: "Tendría más tiempo sin el trabajo.", de: "Ohne die Arbeit hätte ich mehr Zeit." },

  "verb:hacer:Presente":      { es: "Hago deporte tres veces por semana.", de: "Ich treibe dreimal pro Woche Sport." },
  "verb:hacer:Indefinido":    { es: "Hice la comida para todos.", de: "Ich machte das Essen für alle." },
  "verb:hacer:Perfecto":      { es: "¿Has hecho los ejercicios?", de: "Hast du die Übungen gemacht?" },
  "verb:hacer:Condicional":   { es: "Yo haría las cosas de otra manera.", de: "Ich würde die Dinge anders machen." },

  "verb:ir:Presente":         { es: "Voy al gimnasio por la tarde.", de: "Ich gehe nachmittags ins Fitnessstudio." },
  "verb:ir:Indefinido":       { es: "El verano pasado fui a España.", de: "Letzten Sommer fuhr ich nach Spanien." },
  "verb:ir:Perfecto":         { es: "Nunca he ido a Cuba.", de: "Ich bin nie nach Kuba gefahren." },
  "verb:ir:Condicional":      { es: "Iría contigo, pero no puedo.", de: "Ich würde mitkommen, aber ich kann nicht." },

  "verb:poder:Presente":      { es: "No puedo salir esta noche.", de: "Ich kann heute Abend nicht ausgehen." },
  "verb:poder:Indefinido":    { es: "No pude terminar el trabajo.", de: "Ich konnte die Arbeit nicht beenden." },
  "verb:poder:Perfecto":      { es: "Hoy no he podido dormir bien.", de: "Heute habe ich nicht gut schlafen können." },
  "verb:poder:Condicional":   { es: "¿Podrías ayudarme un momento?", de: "Könntest du mir kurz helfen?" },

  "verb:querer:Presente":     { es: "Quiero aprender más vocabulario.", de: "Ich will mehr Wortschatz lernen." },
  "verb:querer:Indefinido":   { es: "Quise llamarte, pero era tarde.", de: "Ich wollte dich anrufen, aber es war spät." },
  "verb:querer:Perfecto":     { es: "Siempre he querido viajar a Perú.", de: "Ich wollte schon immer nach Peru reisen." },
  "verb:querer:Condicional":  { es: "Querría un café con leche.", de: "Ich hätte gern einen Milchkaffee." },

  "verb:saber:Presente":      { es: "No sé dónde está la llave.", de: "Ich weiß nicht, wo der Schlüssel ist." },
  "verb:saber:Indefinido":    { es: "Lo supe ayer por la tarde.", de: "Ich erfuhr es gestern Nachmittag." },
  "verb:saber:Perfecto":      { es: "Nunca he sabido cocinar bien.", de: "Ich habe nie gut kochen können." },
  "verb:saber:Condicional":   { es: "Sabría la respuesta con más tiempo.", de: "Mit mehr Zeit wüsste ich die Antwort." },

  "verb:conocer:Presente":    { es: "Conozco un restaurante muy bueno.", de: "Ich kenne ein sehr gutes Restaurant." },
  "verb:conocer:Indefinido":  { es: "Conocí a mi novia en la universidad.", de: "Ich lernte meine Freundin an der Uni kennen." },
  "verb:conocer:Perfecto":    { es: "He conocido a mucha gente aquí.", de: "Ich habe hier viele Leute kennengelernt." },
  "verb:conocer:Condicional": { es: "Conocería la ciudad mejor viviendo allí.", de: "Ich würde die Stadt besser kennen, wenn ich dort wohnte." },

  "special:gustar": { es: "A mí me gusta mucho el chocolate.", de: "Mir gefällt Schokolade sehr / Ich mag Schokolade sehr." },
  "special:haber":  { es: "En la nevera hay leche y queso.", de: "Im Kühlschrank gibt es Milch und Käse." },

  // ============ Haus & Wohnen ============
  "la habitación":   { es: "Mi habitación es pequeña pero luminosa.", de: "Mein Zimmer ist klein, aber hell." },
  "la cocina":       { es: "Preparamos la cena en la cocina.", de: "Wir bereiten das Abendessen in der Küche zu." },
  "el salón":        { es: "Vemos la televisión en el salón.", de: "Wir sehen im Wohnzimmer fern." },
  "el baño":         { es: "El baño está al final del pasillo.", de: "Das Badezimmer ist am Ende des Flurs." },
  "la ventana":      { es: "Abre la ventana, hace calor.", de: "Mach das Fenster auf, es ist heiß." },
  "la cama":         { es: "Me acuesto en la cama a las once.", de: "Ich lege mich um elf ins Bett." },
  "el armario":      { es: "La ropa está en el armario.", de: "Die Kleidung ist im Schrank." },
  "la mesa":         { es: "Ponemos los platos en la mesa.", de: "Wir stellen die Teller auf den Tisch." },
  "la silla":        { es: "Esta silla es muy cómoda.", de: "Dieser Stuhl ist sehr bequem." },
  "el sofá":         { es: "Me siento en el sofá para leer.", de: "Ich setze mich zum Lesen aufs Sofa." },
  "el jardín":       { es: "En el jardín hay muchas flores.", de: "Im Garten gibt es viele Blumen." },
  "el piso":         { es: "Vivo en un piso con dos amigos.", de: "Ich wohne in einer Wohnung mit zwei Freunden." },
  "el vecino":       { es: "Mi vecino es muy amable.", de: "Mein Nachbar ist sehr freundlich." },
  "luminoso/a":      { es: "El salón es muy luminoso por la mañana.", de: "Das Wohnzimmer ist morgens sehr hell." },
  "acogedor/a":      { es: "Su casa es pequeña pero acogedor.", de: "Ihr Haus ist klein, aber gemütlich." },
  "amueblado/a":     { es: "Busco un piso amueblado.", de: "Ich suche eine möblierte Wohnung." },

  // ============ Essen & Küche ============
  "el desayuno":     { es: "El desayuno es la comida más importante.", de: "Das Frühstück ist die wichtigste Mahlzeit." },
  "la cena":         { es: "La cena es a las nueve.", de: "Das Abendessen ist um neun." },
  "la leche":        { es: "Tomo café con leche por la mañana.", de: "Morgens trinke ich Milchkaffee." },
  "el queso":        { es: "Me gusta el queso manchego.", de: "Ich mag Manchego-Käse." },
  "la carne":        { es: "No como carne los lunes.", de: "Montags esse ich kein Fleisch." },
  "el pescado":      { es: "El pescado está muy fresco hoy.", de: "Der Fisch ist heute sehr frisch." },
  "el huevo":        { es: "Para la tortilla necesito un huevo más.", de: "Für die Tortilla brauche ich noch ein Ei." },
  "el arroz":        { es: "Cocino el arroz con verduras.", de: "Ich koche den Reis mit Gemüse." },
  "la sal":          { es: "Falta un poco de sal.", de: "Es fehlt etwas Salz." },
  "el azúcar":       { es: "No pongo azúcar en el café.", de: "Ich tue keinen Zucker in den Kaffee." },
  "la ensalada":     { es: "De primero quiero una ensalada.", de: "Als Vorspeise möchte ich einen Salat." },
  "el plato":        { es: "Pon el plato en la mesa, por favor.", de: "Stell den Teller bitte auf den Tisch." },
  "el vaso":         { es: "¿Me traes un vaso de agua?", de: "Bringst du mir ein Glas Wasser?" },
  "el cuchillo":     { es: "Corto el pan con el cuchillo.", de: "Ich schneide das Brot mit dem Messer." },
  "el tenedor":      { es: "Se come la pasta con tenedor.", de: "Nudeln isst man mit der Gabel." },
  "la servilleta":   { es: "Necesito una servilleta, por favor.", de: "Ich brauche bitte eine Serviette." },
  "la sartén":       { es: "Frío el huevo en la sartén.", de: "Ich brate das Ei in der Pfanne." },
  "la manzana":      { es: "Como una manzana cada día.", de: "Ich esse jeden Tag einen Apfel." },
  "el tomate":       { es: "La ensalada lleva tomate y cebolla.", de: "Der Salat enthält Tomate und Zwiebel." },
  "la cebolla":      { es: "Primero corto la cebolla en trozos.", de: "Zuerst schneide ich die Zwiebel in Stücke." },
  "el ajo":          { es: "Añade un diente de ajo.", de: "Gib eine Knoblauchzehe dazu." },
  "la patata":       { es: "La tortilla de patata es típica de España.", de: "Die Kartoffeltortilla ist typisch für Spanien." },

  // ============ Charakter & Aussehen ============
  "simpático/a":     { es: "Tu hermano es muy simpático.", de: "Dein Bruder ist sehr sympathisch." },
  "alegre":          { es: "Siempre está alegre por las mañanas.", de: "Morgens ist er immer fröhlich." },
  "tímido/a":        { es: "De pequeño era muy tímido.", de: "Als Kind war ich sehr schüchtern." },
  "trabajador/a":    { es: "Mi compañera es muy trabajador.", de: "Meine Kollegin ist sehr fleißig." },
  "divertido/a":     { es: "El profesor es muy divertido.", de: "Der Lehrer ist sehr lustig." },
  "alto/a":          { es: "Mi padre es muy alto.", de: "Mein Vater ist sehr groß." },
  "rubio/a":         { es: "Su hija es rubio y tiene los ojos azules.", de: "Ihre Tochter ist blond und hat blaue Augen." },
  "la barba":        { es: "Lleva barba desde el invierno.", de: "Er trägt seit dem Winter einen Bart." },
  "las gafas":       { es: "No veo nada sin las gafas.", de: "Ohne die Brille sehe ich nichts." },
  "la ropa":         { es: "Guardo la ropa en el armario.", de: "Ich bewahre die Kleidung im Schrank auf." },
  "la camiseta":     { es: "Llevo una camiseta blanca.", de: "Ich trage ein weißes T-Shirt." },
  "los pantalones":  { es: "Estos pantalones me quedan grandes.", de: "Diese Hose ist mir zu groß." },
  "el coche":        { es: "Vamos en coche a la playa.", de: "Wir fahren mit dem Auto an den Strand." },
  "llevarse bien":   { es: "Es importante llevarse bien con los vecinos.", de: "Es ist wichtig, sich gut mit den Nachbarn zu verstehen." },

  // ============ Alltag, Höflichkeit, Gefühle ============
  "saludar":         { es: "Es de buena educación saludar al entrar.", de: "Es gehört sich, beim Eintreten zu grüßen." },
  "prestar":         { es: "¿Me puedes prestar un bolígrafo?", de: "Kannst du mir einen Kugelschreiber leihen?" },
  "devolver":        { es: "Tengo que devolver el libro mañana.", de: "Ich muss das Buch morgen zurückgeben." },
  "pagar":           { es: "Prefiero pagar con tarjeta.", de: "Ich zahle lieber mit Karte." },
  "comprar":         { es: "Tengo que comprar pan y leche.", de: "Ich muss Brot und Milch kaufen." },
  "el regalo":       { es: "Le compré un regalo por su cumpleaños.", de: "Ich kaufte ihm ein Geschenk zum Geburtstag." },
  "la cuenta":       { es: "Camarero, la cuenta, por favor.", de: "Herr Ober, die Rechnung bitte." },
  "tener prisa":     { es: "No me gusta tener prisa por la mañana.", de: "Ich mag es nicht, morgens in Eile zu sein." },
  "llegar tarde":    { es: "Siento llegar tarde a la reunión.", de: "Tut mir leid, dass ich zu spät zum Treffen komme." },
  "amable":          { es: "El dependiente fue muy amable.", de: "Der Verkäufer war sehr freundlich." },
  "cansado/a":       { es: "Estoy muy cansado después del trabajo.", de: "Nach der Arbeit bin ich sehr müde." },
  "contento/a":      { es: "Estoy contento con el resultado.", de: "Ich bin mit dem Ergebnis zufrieden." },
  "enfadado/a":      { es: "Está enfadado porque llegamos tarde.", de: "Er ist verärgert, weil wir zu spät kamen." },
  "preocupado/a":    { es: "Mi madre está preocupado por el examen.", de: "Meine Mutter ist wegen der Prüfung besorgt." },

  // ============ Gesundheit ============
  "la salud":        { es: "Cuidar la salud es lo más importante.", de: "Auf die Gesundheit zu achten ist das Wichtigste." },
  "doler":           { es: "Después del deporte puede doler la espalda.", de: "Nach dem Sport kann der Rücken wehtun." },
  "la fiebre":       { es: "Tengo fiebre y no voy a clase.", de: "Ich habe Fieber und gehe nicht zum Unterricht." },
  "la gripe":        { es: "Estoy en casa con la gripe.", de: "Ich bin mit Grippe zu Hause." },
  "enfermo/a":       { es: "Mi hermano está enfermo esta semana.", de: "Mein Bruder ist diese Woche krank." },
  "el médico / la médica": { es: "Voy al médico esta tarde.", de: "Ich gehe heute Nachmittag zum Arzt." },
  "la farmacia":     { es: "La farmacia cierra a las ocho.", de: "Die Apotheke schließt um acht." },
  "dormir":          { es: "Necesito dormir ocho horas.", de: "Ich muss acht Stunden schlafen." },
  "hacer deporte":   { es: "Me gusta hacer deporte por la mañana.", de: "Ich mache gern morgens Sport." },
  "estar en forma":  { es: "Corro para estar en forma.", de: "Ich laufe, um fit zu sein." },

  // ============ Lernen & Uni ============
  "el idioma":       { es: "El español es un idioma muy útil.", de: "Spanisch ist eine sehr nützliche Sprache." },
  "aprender":        { es: "Quiero aprender a hablar con fluidez.", de: "Ich will fließend sprechen lernen." },
  "estudiar":        { es: "Tengo que estudiar dos horas cada día.", de: "Ich muss jeden Tag zwei Stunden lernen." },
  "el examen":       { es: "El examen es el lunes por la mañana.", de: "Die Prüfung ist am Montagmorgen." },
  "entender":        { es: "Es difícil entender esta palabra.", de: "Es ist schwierig, dieses Wort zu verstehen." },
  "la palabra":      { es: "Busco la palabra en el diccionario.", de: "Ich suche das Wort im Wörterbuch." },
  "la frase":        { es: "Escribe una frase con este verbo.", de: "Schreib einen Satz mit diesem Verb." },
  "el error":        { es: "Cometí un error en la última pregunta.", de: "Ich machte einen Fehler bei der letzten Frage." },
  "el libro":        { es: "Este libro es muy interesante.", de: "Dieses Buch ist sehr interessant." },
  "escribir":        { es: "Voy a escribir un correo a mi profesora.", de: "Ich werde eine E-Mail an meine Lehrerin schreiben." },
  "leer":            { es: "Me gusta leer el periódico por la mañana.", de: "Ich lese morgens gern die Zeitung." },
  "difícil":         { es: "La gramática española no es difícil.", de: "Die spanische Grammatik ist nicht schwierig." },

  // ============ Freizeit ============
  "el ocio":         { es: "El fin de semana es tiempo de ocio.", de: "Das Wochenende ist Freizeit." },
  "el concierto":    { es: "El concierto empieza a las diez.", de: "Das Konzert beginnt um zehn." },
  "la entrada":      { es: "Compré la entrada por internet.", de: "Ich kaufte die Eintrittskarte im Internet." },
  "la música":       { es: "Escucho música mientras estudio.", de: "Ich höre Musik, während ich lerne." },
  "la película":     { es: "La película dura dos horas.", de: "Der Film dauert zwei Stunden." },
  "correr":          { es: "Salgo a correr por el parque.", de: "Ich gehe im Park laufen." },
  "nadar":           { es: "Aprendí a nadar de pequeño.", de: "Ich lernte als Kind schwimmen." },
  "bailar":          { es: "Nos gusta bailar los sábados.", de: "Wir tanzen gern samstags." },
  "viajar":          { es: "Quiero viajar por Latinoamérica.", de: "Ich möchte durch Lateinamerika reisen." },
  "la bicicleta":    { es: "Voy al trabajo en bicicleta.", de: "Ich fahre mit dem Fahrrad zur Arbeit." },

  // ============ Biografie & Zeit ============
  "nacer":           { es: "Nacer en un pueblo pequeño tiene ventajas.", de: "In einem kleinen Dorf geboren zu werden hat Vorteile." },
  "casarse":         { es: "Mis padres quieren casarse en mayo.", de: "Meine Eltern wollen im Mai heiraten." },
  "mudarse":         { es: "Mudarse a otra ciudad no es fácil.", de: "In eine andere Stadt umzuziehen ist nicht einfach." },
  "el dinero":       { es: "No tengo dinero en efectivo.", de: "Ich habe kein Bargeld." },
  "el trabajo":      { es: "Busco trabajo para el verano.", de: "Ich suche Arbeit für den Sommer." },
  "la vida":         { es: "La vida en la ciudad es más cara.", de: "Das Leben in der Stadt ist teurer." },
  "antes":           { es: "Antes vivíamos en un piso más pequeño.", de: "Früher wohnten wir in einer kleineren Wohnung." },
  "todavía":         { es: "Todavía no he terminado el trabajo.", de: "Ich habe die Arbeit noch nicht beendet." },
  "el cumpleaños":   { es: "Mi cumpleaños es en agosto.", de: "Mein Geburtstag ist im August." },
  "la fiesta":       { es: "La fiesta terminó muy tarde.", de: "Das Fest endete sehr spät." },
  "invitar":         { es: "Quiero invitar a mis amigos el sábado.", de: "Ich möchte am Samstag meine Freunde einladen." },
  "de repente":      { es: "De repente empezó a llover.", de: "Plötzlich fing es an zu regnen." },

  // ============ Básico ============
  "hola":            { es: "Le digo hola a mi vecina cada mañana.", de: "Ich sage meiner Nachbarin jeden Morgen hallo." },
  "adiós":           { es: "Nos dijimos adiós en la estación.", de: "Wir sagten uns am Bahnhof auf Wiedersehen." },
  "gracias":         { es: "Muchas gracias por tu ayuda.", de: "Vielen Dank für deine Hilfe." },
  "por favor":       { es: "¿Me pasas la sal, por favor?", de: "Reichst du mir bitte das Salz?" },
  "sí":              { es: "Le dije que sí a la propuesta.", de: "Ich sagte ja zu dem Vorschlag." },
  "no":              { es: "Hoy no tengo tiempo para salir.", de: "Heute habe ich keine Zeit auszugehen." },
  "perdón":          { es: "Te pido perdón por llegar tarde.", de: "Ich bitte um Entschuldigung, dass ich zu spät komme." },
  "hoy":             { es: "Hoy hace muy buen tiempo.", de: "Heute ist sehr schönes Wetter." },
  "mañana":          { es: "Mañana empiezo un curso nuevo.", de: "Morgen fange ich einen neuen Kurs an." },
  "ahora":           { es: "Ahora no puedo hablar contigo.", de: "Jetzt kann ich nicht mit dir sprechen." },

  // ============ Verbos (Grundformen) ============
  "ser":             { es: "Quiero ser profesor de idiomas.", de: "Ich will Sprachlehrer werden." },
  "estar":           { es: "Prefiero estar en casa cuando llueve.", de: "Ich bin lieber zu Hause, wenn es regnet." },
  "tener":           { es: "Es bueno tener amigos en el extranjero.", de: "Es ist gut, Freunde im Ausland zu haben." },
  "hacer":           { es: "Hay mucho que hacer esta semana.", de: "Diese Woche gibt es viel zu tun." },
  "ir":              { es: "Me apetece ir al cine esta noche.", de: "Ich habe Lust, heute Abend ins Kino zu gehen." },
  "poder":           { es: "Quiero poder hablar sin pensar tanto.", de: "Ich will sprechen können, ohne so viel nachzudenken." },
  "querer":          { es: "Hay que querer para conseguirlo.", de: "Man muss es wollen, um es zu schaffen." },
  "hablar":          { es: "Me gusta hablar con gente nueva.", de: "Ich spreche gern mit neuen Leuten." },
  "comer":           { es: "Vamos a comer algo típico de aquí.", de: "Wir essen etwas Typisches von hier." },
  "vivir":           { es: "Me gustaría vivir cerca del mar.", de: "Ich würde gern in Meeresnähe leben." },
  "saber":           { es: "Es útil saber cocinar.", de: "Es ist nützlich, kochen zu können." },
  "conocer":         { es: "Quiero conocer otros países.", de: "Ich möchte andere Länder kennenlernen." },

  // ============ Personas ============
  "el hombre":       { es: "El hombre de la tienda es muy amable.", de: "Der Mann im Laden ist sehr freundlich." },
  "la mujer":        { es: "La mujer del piso de arriba es médica.", de: "Die Frau aus der Wohnung oben ist Ärztin." },
  "el amigo / la amiga": { es: "Mi mejor amigo vive en Sevilla.", de: "Mein bester Freund wohnt in Sevilla." },
  "el niño / la niña":   { es: "El niño juega en el parque.", de: "Das Kind spielt im Park." },
  "la familia":      { es: "Toda la familia come junta los domingos.", de: "Die ganze Familie isst sonntags zusammen." },
  "el padre":        { es: "Mi padre trabaja en un banco.", de: "Mein Vater arbeitet in einer Bank." },
  "la madre":        { es: "Mi madre cocina muy bien.", de: "Meine Mutter kocht sehr gut." },

  // ============ Tiempo ============
  "el día":          { es: "Cada día estudio un poco de español.", de: "Jeden Tag lerne ich ein bisschen Spanisch." },
  "la semana":       { es: "La semana que viene tengo un examen.", de: "Nächste Woche habe ich eine Prüfung." },
  "el mes":          { es: "El mes de agosto es muy caluroso.", de: "Der Monat August ist sehr heiß." },
  "el año":          { es: "Este año quiero viajar a México.", de: "Dieses Jahr möchte ich nach Mexiko reisen." },
  "la hora":         { es: "¿Tienes hora? Mi reloj no funciona.", de: "Hast du die Uhrzeit? Meine Uhr geht nicht." },

  // ============ Lugares ============
  "la casa":         { es: "Mi casa está cerca del parque.", de: "Mein Haus liegt in der Nähe des Parks." },
  "la ciudad":       { es: "La ciudad es más ruidosa que el pueblo.", de: "Die Stadt ist lauter als das Dorf." },
  "la escuela":      { es: "Los niños van a la escuela en autobús.", de: "Die Kinder fahren mit dem Bus zur Schule." },
  "la calle":        { es: "La calle está cerrada por obras.", de: "Die Straße ist wegen Bauarbeiten gesperrt." },

  // ============ Ubicación ============
  "encima de / sobre":     { es: "El libro está encima de la mesa.", de: "Das Buch liegt auf dem Tisch." },
  "debajo de":             { es: "El gato duerme debajo de la cama.", de: "Die Katze schläft unter dem Bett." },
  "al lado de / junto a":  { es: "La farmacia está al lado de la panadería.", de: "Die Apotheke ist neben der Bäckerei." },
  "a la izquierda de":     { es: "El museo está a la izquierda de la plaza.", de: "Das Museum ist links vom Platz." },
  "a la derecha de":       { es: "La cocina está a la derecha de la entrada.", de: "Die Küche ist rechts vom Eingang." },
  "delante de":            { es: "Hay un coche delante de la casa.", de: "Vor dem Haus steht ein Auto." },
  "detrás de":             { es: "El jardín está detrás de la casa.", de: "Der Garten liegt hinter dem Haus." },
  "entre":                 { es: "La silla está entre la mesa y la ventana.", de: "Der Stuhl steht zwischen Tisch und Fenster." },
  "dentro de":             { es: "Las llaves están dentro de la bolsa.", de: "Die Schlüssel sind in der Tasche." },
  "cerca de":              { es: "Vivo cerca de la universidad.", de: "Ich wohne in der Nähe der Universität." },
  "lejos de":              { es: "Mi trabajo está lejos de mi casa.", de: "Meine Arbeit ist weit von meinem Zuhause entfernt." },
  "aquí":                  { es: "Aquí hace más frío que en Madrid.", de: "Hier ist es kälter als in Madrid." },
  "ahí":                   { es: "Deja el paquete ahí, por favor.", de: "Lass das Paket bitte da." },
  "allí":                  { es: "Allí venden fruta muy fresca.", de: "Dort verkaufen sie sehr frisches Obst." },
  "allá":                  { es: "Vamos allá en autobús.", de: "Wir fahren mit dem Bus dorthin." },

  // ============ El cuerpo ============
  "la cabeza":       { es: "Me duele la cabeza después del examen.", de: "Nach der Prüfung habe ich Kopfschmerzen." },
  "la cara":         { es: "Se lava la cara con agua fría.", de: "Er wäscht sich das Gesicht mit kaltem Wasser." },
  "el pelo":         { es: "Lleva el pelo muy corto.", de: "Sie trägt die Haare sehr kurz." },
  "el ojo":          { es: "Le entró algo en el ojo.", de: "Ihm ist etwas ins Auge geraten." },
  "la oreja":        { es: "El niño se tapa la oreja con la mano.", de: "Das Kind hält sich das Ohr mit der Hand zu." },
  "la nariz":        { es: "Con el resfriado me gotea la nariz.", de: "Bei der Erkältung läuft mir die Nase." },
  "la boca":         { es: "Abre la boca, dice el dentista.", de: "Mach den Mund auf, sagt der Zahnarzt." },
  "el diente":       { es: "Me duele un diente desde ayer.", de: "Seit gestern tut mir ein Zahn weh." },
  "la lengua":       { es: "Me quemé la lengua con el café.", de: "Ich habe mir die Zunge am Kaffee verbrannt." },
  "el cuello":       { es: "Después de dormir mal me duele el cuello.", de: "Nach schlechtem Schlaf tut mir der Hals weh." },
  "la garganta":     { es: "Tengo la garganta irritada.", de: "Mein Hals ist gereizt." },
  "el hombro":       { es: "Llevo la mochila en el hombro.", de: "Ich trage den Rucksack auf der Schulter." },
  "el brazo":        { es: "Se rompió el brazo jugando al fútbol.", de: "Er brach sich beim Fußball den Arm." },
  "la mano":         { es: "Le dio la mano al llegar.", de: "Er gab ihm bei der Ankunft die Hand." },
  "el dedo":         { es: "Me corté un dedo con el cuchillo.", de: "Ich habe mir mit dem Messer in den Finger geschnitten." },
  "el pecho":        { es: "Siente dolor en el pecho al respirar.", de: "Er spürt beim Atmen Schmerzen in der Brust." },
  "la espalda":      { es: "Me duele la espalda de estar sentado.", de: "Vom Sitzen tut mir der Rücken weh." },
  "la pierna":       { es: "Le duele la pierna después de correr.", de: "Nach dem Laufen tut ihm das Bein weh." },
  "la rodilla":      { es: "Se hizo daño en la rodilla.", de: "Er hat sich am Knie verletzt." },
  "el pie":          { es: "Me duele el pie con estos zapatos.", de: "Mit diesen Schuhen tut mir der Fuß weh." },
  "el corazón":      { es: "El corazón late más rápido al correr.", de: "Beim Laufen schlägt das Herz schneller." },
  "la piel":         { es: "En verano protejo la piel del sol.", de: "Im Sommer schütze ich die Haut vor der Sonne." },
  "la sangre":       { es: "El análisis de sangre salió bien.", de: "Die Blutuntersuchung war in Ordnung." },
  "el estómago":     { es: "Me duele el estómago después de comer.", de: "Nach dem Essen tut mir der Magen weh." },
  "la uña":          { es: "Se muerde la uña cuando está nervioso.", de: "Er kaut am Fingernagel, wenn er nervös ist." },

  // ============ Antes y ahora ============
  "entonces":        { es: "Entonces no existían los móviles.", de: "Damals gab es keine Handys." },
  "ya no":           { es: "Ya no vivo en el centro.", de: "Ich wohne nicht mehr im Zentrum." },
  "hoy en día":      { es: "Hoy en día todo el mundo tiene internet.", de: "Heutzutage hat jeder Internet." },
  "la época":        { es: "En aquella época la vida era más lenta.", de: "In jener Zeit war das Leben langsamer." },
  "el siglo":        { es: "El siglo pasado cambió mucho el mundo.", de: "Das letzte Jahrhundert hat die Welt stark verändert." },
  "la infancia":     { es: "Pasé la infancia en un pueblo pequeño.", de: "Ich verbrachte die Kindheit in einem kleinen Dorf." },
  "la juventud":     { es: "En su juventud viajó por toda Europa.", de: "In ihrer Jugend reiste sie durch ganz Europa." },
  "la vejez":        { es: "La vejez trae mucha experiencia.", de: "Das hohe Alter bringt viel Erfahrung." },
  "el bebé":         { es: "El bebé duerme toda la tarde.", de: "Das Baby schläft den ganzen Nachmittag." },
  "la sociedad":     { es: "La sociedad ha cambiado mucho.", de: "Die Gesellschaft hat sich stark verändert." },
  "el gobierno":     { es: "El gobierno aprobó una ley nueva.", de: "Die Regierung verabschiedete ein neues Gesetz." },
  "la ley":          { es: "La ley entró en vigor en enero.", de: "Das Gesetz trat im Januar in Kraft." },
  "el derecho":      { es: "Todos tienen derecho a la educación.", de: "Alle haben ein Recht auf Bildung." },
  "la libertad":     { es: "La libertad de expresión es fundamental.", de: "Die Meinungsfreiheit ist grundlegend." },
  "la educación":    { es: "La educación es gratuita en muchos países.", de: "Bildung ist in vielen Ländern kostenlos." },
  "la democracia":   { es: "La democracia llegó a España en 1978.", de: "Die Demokratie kam 1978 nach Spanien." },
  "la frontera":     { es: "Cruzamos la frontera por la mañana.", de: "Wir überquerten morgens die Grenze." },
  "la población":    { es: "La población de la ciudad creció mucho.", de: "Die Bevölkerung der Stadt wuchs stark." },
  "prohibido/a":     { es: "Está prohibido fumar dentro del edificio.", de: "Im Gebäude ist das Rauchen verboten." },
  "el aeropuerto":   { es: "El aeropuerto está lejos del centro.", de: "Der Flughafen liegt weit vom Zentrum entfernt." },
  "el avión":        { es: "El avión sale a las siete de la mañana.", de: "Das Flugzeug startet um sieben Uhr morgens." },
  "la tecnología":   { es: "La tecnología avanza muy rápido.", de: "Die Technik entwickelt sich sehr schnell." },
  "el invento":      { es: "El invento de la rueda lo cambió todo.", de: "Die Erfindung des Rades veränderte alles." },
  "la naturaleza":   { es: "Me gusta pasear por la naturaleza.", de: "Ich spaziere gern in der Natur." },
  "el medio ambiente": { es: "Hay que cuidar el medio ambiente.", de: "Man muss die Umwelt schützen." },

  // ============ Biografía ============
  "divorciarse":     { es: "Sus padres decidieron divorciarse.", de: "Ihre Eltern beschlossen, sich scheiden zu lassen." },
  "enamorarse":      { es: "Es fácil enamorarse en primavera.", de: "Im Frühling verliebt man sich leicht." },
  "jubilarse":       { es: "Mi abuelo va a jubilarse este año.", de: "Mein Großvater geht dieses Jahr in Rente." },
  "morir":           { es: "Las plantas pueden morir sin agua.", de: "Pflanzen können ohne Wasser sterben." },
  "ganar":           { es: "Quiere ganar más dinero este año.", de: "Er will dieses Jahr mehr Geld verdienen." },
  "perder":          { es: "Odio perder las llaves.", de: "Ich hasse es, die Schlüssel zu verlieren." },
  "conseguir":       { es: "Es difícil conseguir entradas.", de: "Es ist schwer, Karten zu bekommen." },
  "empezar":         { es: "Voy a empezar un curso de italiano.", de: "Ich fange einen Italienischkurs an." },
  "terminar":        { es: "Tengo que terminar el trabajo hoy.", de: "Ich muss die Arbeit heute beenden." },
  "decidir":         { es: "Es hora de decidir qué estudiar.", de: "Es ist Zeit zu entscheiden, was man studiert." },
  "recibir":         { es: "Espero recibir una respuesta pronto.", de: "Ich hoffe, bald eine Antwort zu erhalten." },
  "visitar":         { es: "Quiero visitar a mis abuelos.", de: "Ich möchte meine Großeltern besuchen." },
  "el apellido":     { es: "Mi apellido es difícil de pronunciar.", de: "Mein Nachname ist schwer auszusprechen." },
  "el nombre":       { es: "Escribe tu nombre en la primera línea.", de: "Schreib deinen Namen in die erste Zeile." },
  "la carrera":      { es: "Terminó la carrera en cuatro años.", de: "Sie beendete das Studium in vier Jahren." },
  "el éxito":        { es: "La película tuvo mucho éxito.", de: "Der Film hatte großen Erfolg." },
  "el premio":       { es: "Ganó un premio muy importante.", de: "Er gewann einen sehr wichtigen Preis." },
  "la empresa":      { es: "Trabajo en una empresa pequeña.", de: "Ich arbeite in einem kleinen Unternehmen." },
  "el hospital":     { es: "Nació en el hospital de la ciudad.", de: "Sie wurde im Krankenhaus der Stadt geboren." },
  "la playa":        { es: "En verano vamos a la playa.", de: "Im Sommer fahren wir an den Strand." },
  "el mar":          { es: "El mar está muy tranquilo hoy.", de: "Das Meer ist heute sehr ruhig." },
  "famoso/a":        { es: "Es un actor muy famoso.", de: "Er ist ein sehr berühmter Schauspieler." },
};
