// Vokabeln — einfach erweiterbar.
// Neues Wort: { es: "Spanisch", de: "Deutsch", cat: "Kategorie" } in die Liste einfügen.
// cat ist frei wählbar (dient zum Filtern nach Themen).

const VOCAB = [
  // --- Básico ---
  { es: "hola", de: "hallo", cat: "Básico" },
  { es: "adiós", de: "tschüss / auf Wiedersehen", cat: "Básico" },
  { es: "gracias", de: "danke", cat: "Básico" },
  { es: "por favor", de: "bitte", cat: "Básico" },
  { es: "sí", de: "ja", cat: "Básico" },
  { es: "no", de: "nein", cat: "Básico" },
  { es: "perdón", de: "Entschuldigung", cat: "Básico" },
  { es: "hoy", de: "heute", cat: "Básico" },
  { es: "mañana", de: "morgen / Vormittag", cat: "Básico" },
  { es: "ahora", de: "jetzt", cat: "Básico" },

  // --- Verbos ---
  { es: "ser", de: "sein (dauerhaft)", cat: "Verbos" },
  { es: "estar", de: "sein (Zustand/Ort)", cat: "Verbos" },
  { es: "tener", de: "haben", cat: "Verbos" },
  { es: "hacer", de: "machen / tun", cat: "Verbos" },
  { es: "ir", de: "gehen", cat: "Verbos" },
  { es: "poder", de: "können", cat: "Verbos" },
  { es: "querer", de: "wollen / lieben", cat: "Verbos" },
  { es: "hablar", de: "sprechen", cat: "Verbos" },
  { es: "comer", de: "essen", cat: "Verbos" },
  { es: "vivir", de: "leben / wohnen", cat: "Verbos" },
  { es: "saber", de: "wissen", cat: "Verbos" },
  { es: "conocer", de: "kennen", cat: "Verbos" },

  // --- Personas ---
  { es: "el hombre", de: "der Mann", cat: "Personas" },
  { es: "la mujer", de: "die Frau", cat: "Personas" },
  { es: "el amigo / la amiga", de: "der Freund / die Freundin", cat: "Personas" },
  { es: "el niño / la niña", de: "das Kind (Junge/Mädchen)", cat: "Personas" },
  { es: "la familia", de: "die Familie", cat: "Personas" },
  { es: "el padre", de: "der Vater", cat: "Personas" },
  { es: "la madre", de: "die Mutter", cat: "Personas" },

  // --- Tiempo ---
  { es: "el día", de: "der Tag", cat: "Tiempo" },
  { es: "la semana", de: "die Woche", cat: "Tiempo" },
  { es: "el mes", de: "der Monat", cat: "Tiempo" },
  { es: "el año", de: "das Jahr", cat: "Tiempo" },
  { es: "la hora", de: "die Stunde / Uhrzeit", cat: "Tiempo" },

  // --- Lugares ---
  { es: "la casa", de: "das Haus", cat: "Lugares" },
  { es: "la ciudad", de: "die Stadt", cat: "Lugares" },
  { es: "el trabajo", de: "die Arbeit", cat: "Lugares" },
  { es: "la escuela", de: "die Schule", cat: "Lugares" },
  { es: "la calle", de: "die Straße", cat: "Lugares" },

  // --- Comida ---
  { es: "el agua", de: "das Wasser", cat: "Comida" },
  { es: "el pan", de: "das Brot", cat: "Comida" },
  { es: "la comida", de: "das Essen / die Mahlzeit", cat: "Comida" },
  { es: "el café", de: "der Kaffee", cat: "Comida" },

  // --- Ubicación (Ortsangaben) --- Quelle: uni/spanisch/Grammatik/Ortsvokabeln + Ortsadverbien
  { es: "encima de / sobre", de: "auf", cat: "Ubicación" },
  { es: "debajo de", de: "unter", cat: "Ubicación" },
  { es: "al lado de / junto a", de: "neben", cat: "Ubicación" },
  { es: "a la izquierda de", de: "links von", cat: "Ubicación" },
  { es: "a la derecha de", de: "rechts von", cat: "Ubicación" },
  { es: "delante de", de: "vor", cat: "Ubicación" },
  { es: "detrás de", de: "hinter", cat: "Ubicación" },
  { es: "entre", de: "zwischen", cat: "Ubicación" },
  { es: "dentro de", de: "in / innerhalb", cat: "Ubicación" },
  { es: "cerca de", de: "nah bei / in der Nähe von", cat: "Ubicación" },
  { es: "lejos de", de: "weit von", cat: "Ubicación" },
  { es: "aquí", de: "hier (beim Sprecher)", cat: "Ubicación" },
  { es: "ahí", de: "da / dort (beim Hörer)", cat: "Ubicación" },
  { es: "allí", de: "dort (konkreter Ort)", cat: "Ubicación" },
  { es: "allá", de: "dort drüben (Richtung)", cat: "Ubicación" },

  // --- El cuerpo (Körper & Körperteile) ---
  { es: "la cabeza", de: "der Kopf", cat: "El cuerpo" },
  { es: "la cara", de: "das Gesicht", cat: "El cuerpo" },
  { es: "el pelo", de: "das Haar / die Haare", cat: "El cuerpo" },
  { es: "la frente", de: "die Stirn", cat: "El cuerpo" },
  { es: "el ojo", de: "das Auge", cat: "El cuerpo" },
  { es: "la ceja", de: "die Augenbraue", cat: "El cuerpo" },
  { es: "la pestaña", de: "die Wimper", cat: "El cuerpo" },
  { es: "la oreja", de: "das Ohr", cat: "El cuerpo" },
  { es: "la nariz", de: "die Nase", cat: "El cuerpo" },
  { es: "la mejilla", de: "die Wange", cat: "El cuerpo" },
  { es: "la boca", de: "der Mund", cat: "El cuerpo" },
  { es: "el labio", de: "die Lippe", cat: "El cuerpo" },
  { es: "el diente", de: "der Zahn", cat: "El cuerpo" },
  { es: "la lengua", de: "die Zunge", cat: "El cuerpo" },
  { es: "la barbilla", de: "das Kinn", cat: "El cuerpo" },
  { es: "el cuello", de: "der Hals", cat: "El cuerpo" },
  { es: "la garganta", de: "der Hals / Rachen (innen)", cat: "El cuerpo" },
  { es: "el hombro", de: "die Schulter", cat: "El cuerpo" },
  { es: "el brazo", de: "der Arm", cat: "El cuerpo" },
  { es: "el codo", de: "der Ellbogen", cat: "El cuerpo" },
  { es: "la muñeca", de: "das Handgelenk", cat: "El cuerpo" },
  { es: "la mano", de: "die Hand", cat: "El cuerpo" },
  { es: "el dedo", de: "der Finger", cat: "El cuerpo" },
  { es: "la uña", de: "der Fingernagel", cat: "El cuerpo" },
  { es: "el pecho", de: "die Brust", cat: "El cuerpo" },
  { es: "la espalda", de: "der Rücken", cat: "El cuerpo" },
  { es: "el estómago", de: "der Magen", cat: "El cuerpo" },
  { es: "la barriga", de: "der Bauch", cat: "El cuerpo" },
  { es: "la cadera", de: "die Hüfte", cat: "El cuerpo" },
  { es: "la pierna", de: "das Bein", cat: "El cuerpo" },
  { es: "la rodilla", de: "das Knie", cat: "El cuerpo" },
  { es: "el tobillo", de: "der Knöchel", cat: "El cuerpo" },
  { es: "el pie", de: "der Fuß", cat: "El cuerpo" },
  { es: "el dedo del pie", de: "der Zeh", cat: "El cuerpo" },
  { es: "el corazón", de: "das Herz", cat: "El cuerpo" },
  { es: "el hueso", de: "der Knochen", cat: "El cuerpo" },
  { es: "la piel", de: "die Haut", cat: "El cuerpo" },
  { es: "la sangre", de: "das Blut", cat: "El cuerpo" },
];
