// Vokabeln — einfach erweiterbar.
// Neues Wort: { es: "Spanisch", de: "Deutsch", cat: "Kategorie" } in die Liste einfügen.
// cat ist frei wählbar (dient zum Filtern nach Themen).

const VOCAB = [
  // --- Básico ---
  { es: "hola", de: "hallo", cat: "Básico" },
  { es: "adiós", de: "tschüss / auf Wiedersehen", cat: "Básico" },
  { es: "gracias", de: "danke", cat: "Básico" },
  { es: "por favor", de: "bitte", cat: "Básico" },
  { es: "sí", de: "ja", cat: "Básico" },
  { es: "no", de: "nein", cat: "Básico" },
  { es: "perdón", de: "Entschuldigung", cat: "Básico" },
  { es: "hoy", de: "heute", cat: "Básico" },
  { es: "mañana", de: "morgen / Vormittag", cat: "Básico" },
  { es: "ahora", de: "jetzt", cat: "Básico" },

  // --- Verbos ---
  { es: "ser", de: "sein (dauerhaft)", cat: "Verbos" },
  { es: "estar", de: "sein (Zustand/Ort)", cat: "Verbos" },
  { es: "tener", de: "haben", cat: "Verbos" },
  { es: "hacer", de: "machen / tun", cat: "Verbos" },
  { es: "ir", de: "gehen", cat: "Verbos" },
  { es: "poder", de: "können", cat: "Verbos" },
  { es: "querer", de: "wollen / lieben", cat: "Verbos" },
  { es: "hablar", de: "sprechen", cat: "Verbos" },
  { es: "comer", de: "essen", cat: "Verbos" },
  { es: "vivir", de: "leben / wohnen", cat: "Verbos" },
  { es: "saber", de: "wissen", cat: "Verbos" },
  { es: "conocer", de: "kennen", cat: "Verbos" },

  // --- Personas ---
  { es: "el hombre", de: "der Mann", cat: "Personas" },
  { es: "la mujer", de: "die Frau", cat: "Personas" },
  { es: "el amigo / la amiga", de: "der Freund / die Freundin", cat: "Personas" },
  { es: "el niño / la niña", de: "das Kind (Junge/Mädchen)", cat: "Personas" },
  { es: "la familia", de: "die Familie", cat: "Personas" },
  { es: "el padre", de: "der Vater", cat: "Personas" },
  { es: "la madre", de: "die Mutter", cat: "Personas" },

  // --- Tiempo ---
  { es: "el día", de: "der Tag", cat: "Tiempo" },
  { es: "la semana", de: "die Woche", cat: "Tiempo" },
  { es: "el mes", de: "der Monat", cat: "Tiempo" },
  { es: "el año", de: "das Jahr", cat: "Tiempo" },
  { es: "la hora", de: "die Stunde / Uhrzeit", cat: "Tiempo" },

  // --- Lugares ---
  { es: "la casa", de: "das Haus", cat: "Lugares" },
  { es: "la ciudad", de: "die Stadt", cat: "Lugares" },
  { es: "el trabajo", de: "die Arbeit", cat: "Lugares" },
  { es: "la escuela", de: "die Schule", cat: "Lugares" },
  { es: "la calle", de: "die Straße", cat: "Lugares" },

  // --- Comida --- Quelle: uni/spanisch/Vokabeln/Unit-7-Comes-de-todo (Aula Plus 2, Glosario S. 267–269)
  // „+" markiert Wörter, die NICHT im Kursglossar stehen, aber zum Alltagswortschatz gehören.
  { es: "el agua", de: "das Wasser", cat: "Comida" },
  { es: "el pan", de: "das Brot", cat: "Comida" },
  { es: "la comida", de: "das Essen / die Mahlzeit", cat: "Comida" },
  { es: "el café", de: "der Kaffee", cat: "Comida" },
  // Mahlzeiten
  { es: "el desayuno", de: "das Frühstück", cat: "Comida" },              // +
  { es: "desayunar", de: "frühstücken", cat: "Comida" },
  { es: "el almuerzo", de: "das Mittagessen", cat: "Comida" },            // +
  { es: "la merienda", de: "der Nachmittagssnack", cat: "Comida" },
  { es: "la cena", de: "das Abendessen", cat: "Comida" },
  // Frühstück & Milchprodukte
  { es: "la leche", de: "die Milch", cat: "Comida" },
  { es: "el yogur", de: "der Joghurt", cat: "Comida" },
  { es: "la mantequilla", de: "die Butter", cat: "Comida" },
  { es: "el queso", de: "der Käse", cat: "Comida" },
  { es: "los cereales", de: "die Cerealien / Müsli", cat: "Comida" },
  { es: "la galleta", de: "der Keks", cat: "Comida" },
  { es: "la tostada", de: "der Toast", cat: "Comida" },
  { es: "la magdalena", de: "der Muffin", cat: "Comida" },
  { es: "la mermelada", de: "die Marmelade", cat: "Comida" },             // +
  { es: "el zumo", de: "der Saft", cat: "Comida" },                       // +
  { es: "el té", de: "der Tee", cat: "Comida" },                          // +
  // Fleisch & Fisch
  { es: "la carne", de: "das Fleisch", cat: "Comida" },
  { es: "la ternera", de: "das Rindfleisch / Kalbfleisch", cat: "Comida" },
  { es: "el pollo", de: "das Hähnchen", cat: "Comida" },                  // +
  { es: "el cerdo", de: "das Schweinefleisch", cat: "Comida" },           // +
  { es: "el jamón", de: "der Schinken", cat: "Comida" },                  // +
  { es: "el embutido", de: "die Wurst / Wurstwaren", cat: "Comida" },
  { es: "el bistec", de: "das Steak", cat: "Comida" },
  { es: "el pescado", de: "der Fisch (als Speise)", cat: "Comida" },
  { es: "el marisco", de: "die Meeresfrüchte", cat: "Comida" },
  { es: "el atún", de: "der Thunfisch", cat: "Comida" },
  { es: "el huevo", de: "das Ei", cat: "Comida" },
  // Grundnahrungsmittel & Gewürze
  { es: "el arroz", de: "der Reis", cat: "Comida" },
  { es: "la pasta", de: "die Nudeln / Teigwaren", cat: "Comida" },
  { es: "los macarrones", de: "die Makkaroni", cat: "Comida" },
  { es: "la sal", de: "das Salz", cat: "Comida" },
  { es: "la pimienta", de: "der Pfeffer (Gewürz)", cat: "Comida" },
  { es: "el azúcar", de: "der Zucker", cat: "Comida" },                   // +
  { es: "el aceite de oliva", de: "das Olivenöl", cat: "Comida" },
  { es: "el vinagre", de: "der Essig", cat: "Comida" },
  { es: "la miel", de: "der Honig", cat: "Comida" },
  { es: "la harina", de: "das Mehl", cat: "Comida" },                     // +
  // Gerichte
  { es: "la ensalada", de: "der Salat (Gericht)", cat: "Comida" },
  { es: "la sopa", de: "die Suppe", cat: "Comida" },                      // +
  { es: "la crema", de: "die Creme / die Cremesuppe", cat: "Comida" },
  { es: "la tortilla de patatas", de: "die spanische Kartoffeltortilla", cat: "Comida" },
  { es: "el gazpacho", de: "die kalte Gemüsesuppe (Gazpacho)", cat: "Comida" },
  { es: "la tarta", de: "die Torte / der Kuchen", cat: "Comida" },
  { es: "el postre", de: "die Nachspeise", cat: "Comida" },               // +
  { es: "la hamburguesa", de: "der Hamburger", cat: "Comida" },

  // --- Frutas y verduras --- Quelle: Unit 7 (+ ergänzte Grundfrüchte)
  { es: "la fruta", de: "das Obst / die Frucht", cat: "Frutas y verduras" },   // +
  { es: "la verdura", de: "das Gemüse", cat: "Frutas y verduras" },
  { es: "la manzana", de: "der Apfel", cat: "Frutas y verduras" },
  { es: "la naranja", de: "die Orange", cat: "Frutas y verduras" },            // +
  { es: "el plátano", de: "die Banane", cat: "Frutas y verduras" },            // +
  { es: "la fresa", de: "die Erdbeere", cat: "Frutas y verduras" },            // +
  { es: "la uva", de: "die Weintraube", cat: "Frutas y verduras" },            // +
  { es: "la pera", de: "die Birne", cat: "Frutas y verduras" },                // +
  { es: "el melocotón", de: "der Pfirsich", cat: "Frutas y verduras" },        // +
  { es: "la sandía", de: "die Wassermelone", cat: "Frutas y verduras" },       // +
  { es: "el melón", de: "die Melone", cat: "Frutas y verduras" },
  { es: "la cereza", de: "die Kirsche", cat: "Frutas y verduras" },
  { es: "el limón", de: "die Zitrone", cat: "Frutas y verduras" },
  { es: "la lechuga", de: "der Kopfsalat", cat: "Frutas y verduras" },
  { es: "la patata", de: "die Kartoffel", cat: "Frutas y verduras" },
  { es: "el tomate", de: "die Tomate", cat: "Frutas y verduras" },
  { es: "la cebolla", de: "die Zwiebel", cat: "Frutas y verduras" },
  { es: "el ajo", de: "der Knoblauch", cat: "Frutas y verduras" },
  { es: "la zanahoria", de: "die Karotte", cat: "Frutas y verduras" },
  { es: "los guisantes", de: "die Erbsen", cat: "Frutas y verduras" },
  { es: "el pepino", de: "die Gurke", cat: "Frutas y verduras" },
  { es: "el pimiento", de: "die Paprika (Gemüse)", cat: "Frutas y verduras" },
  { es: "la alcachofa", de: "die Artischocke", cat: "Frutas y verduras" },
  { es: "la col", de: "der Kohl", cat: "Frutas y verduras" },
  { es: "el aguacate", de: "die Avocado", cat: "Frutas y verduras" },
  { es: "las judías", de: "die Bohnen", cat: "Frutas y verduras" },
  { es: "los garbanzos", de: "die Kichererbsen", cat: "Frutas y verduras" },
  { es: "las legumbres", de: "die Hülsenfrüchte", cat: "Frutas y verduras" },
  { es: "la aceituna", de: "die Olive", cat: "Frutas y verduras" },
  { es: "el champiñón", de: "der Champignon", cat: "Frutas y verduras" },      // +
  { es: "el perejil", de: "die Petersilie", cat: "Frutas y verduras" },
  { es: "el cilantro", de: "der Koriander", cat: "Frutas y verduras" },
  { es: "la almendra", de: "die Mandel", cat: "Frutas y verduras" },
  { es: "los frutos secos", de: "die Nüsse / Trockenfrüchte", cat: "Frutas y verduras" },

  // --- La cocina (Besteck, Geschirr, Kochen) --- Quelle: Unit 7 Léxico (+ Tischgedeck ergänzt)
  { es: "el tenedor", de: "die Gabel", cat: "La cocina" },
  { es: "el cuchillo", de: "das Messer", cat: "La cocina" },
  { es: "la cuchara", de: "der Löffel", cat: "La cocina" },                    // +
  { es: "la cucharita", de: "der Teelöffel", cat: "La cocina" },               // +
  { es: "el cucharón", de: "die Schöpfkelle", cat: "La cocina" },
  { es: "el plato", de: "der Teller", cat: "La cocina" },                      // +
  { es: "el vaso", de: "das Glas (Trinkglas)", cat: "La cocina" },             // +
  { es: "la copa", de: "das Stielglas / Weinglas", cat: "La cocina" },         // +
  { es: "la taza", de: "die Tasse", cat: "La cocina" },                        // +
  { es: "el bol", de: "die Schüssel", cat: "La cocina" },
  { es: "la bandeja", de: "das Tablett", cat: "La cocina" },
  { es: "la servilleta", de: "die Serviette", cat: "La cocina" },              // +
  { es: "el mantel", de: "die Tischdecke", cat: "La cocina" },                 // +
  { es: "la sartén", de: "die Pfanne", cat: "La cocina" },
  { es: "la cazuela", de: "der Schmortopf", cat: "La cocina" },
  { es: "la olla", de: "der Topf", cat: "La cocina" },
  { es: "la tabla de cortar", de: "das Schneidebrett", cat: "La cocina" },
  { es: "el escurridor", de: "das Sieb / Abtropfsieb", cat: "La cocina" },
  { es: "la botella", de: "die Flasche", cat: "La cocina" },
  { es: "la lata", de: "die Dose", cat: "La cocina" },
  { es: "el bote", de: "das Glas / die Dose (Behälter)", cat: "La cocina" },
  { es: "la caja", de: "die Schachtel / Kiste", cat: "La cocina" },
  { es: "la receta", de: "das Rezept", cat: "La cocina" },                     // +
  { es: "cocinar", de: "kochen (zubereiten)", cat: "La cocina" },              // +
  { es: "pelar", de: "schälen", cat: "La cocina" },
  { es: "cortar", de: "schneiden", cat: "La cocina" },
  { es: "hervir", de: "kochen (sieden)", cat: "La cocina" },
  { es: "freír", de: "braten / frittieren", cat: "La cocina" },
  { es: "asar", de: "im Ofen braten", cat: "La cocina" },
  { es: "calentar", de: "aufwärmen", cat: "La cocina" },
  { es: "congelar", de: "einfrieren", cat: "La cocina" },
  { es: "mezclar", de: "mischen", cat: "La cocina" },
  { es: "añadir", de: "hinzufügen", cat: "La cocina" },
  { es: "batir", de: "schlagen (verquirlen)", cat: "La cocina" },
  { es: "lavar", de: "waschen", cat: "La cocina" },
  { es: "probar", de: "probieren", cat: "La cocina" },

  // --- La casa --- Quelle: uni/spanisch/Vokabeln/Unit-4-Hogar-dulce-hogar (Aula Plus 2, Glosario S. 263–265)
  // Räume
  { es: "la habitación", de: "das Zimmer", cat: "La casa" },
  { es: "la cocina", de: "die Küche", cat: "La casa" },
  { es: "el salón", de: "das Wohnzimmer", cat: "La casa" },
  { es: "el comedor", de: "das Esszimmer", cat: "La casa" },                   // +
  { es: "el dormitorio", de: "das Schlafzimmer", cat: "La casa" },             // +
  { es: "el despacho", de: "das Arbeitszimmer", cat: "La casa" },
  { es: "el baño", de: "das Badezimmer", cat: "La casa" },
  { es: "el lavadero", de: "die Waschküche", cat: "La casa" },
  { es: "el vestidor", de: "der Ankleideraum", cat: "La casa" },
  { es: "el pasillo", de: "der Flur", cat: "La casa" },                        // +
  { es: "el garaje", de: "die Garage", cat: "La casa" },
  { es: "la terraza", de: "die Terrasse", cat: "La casa" },
  { es: "el balcón", de: "der Balkon", cat: "La casa" },
  { es: "la planta baja", de: "das Erdgeschoss", cat: "La casa" },
  { es: "la planta", de: "die Etage / die Pflanze", cat: "La casa" },
  // Möbel
  { es: "el mueble", de: "das Möbelstück", cat: "La casa" },                   // +
  { es: "el sofá", de: "das Sofa", cat: "La casa" },
  { es: "el sillón", de: "der Sessel", cat: "La casa" },
  { es: "la mesa", de: "der Tisch", cat: "La casa" },                          // +
  { es: "la mesa de centro", de: "der Couchtisch", cat: "La casa" },
  { es: "la silla", de: "der Stuhl", cat: "La casa" },
  { es: "la estantería", de: "das Regal", cat: "La casa" },
  { es: "el armario", de: "der Schrank", cat: "La casa" },
  { es: "la cama", de: "das Bett", cat: "La casa" },
  { es: "la mesilla de noche", de: "der Nachttisch", cat: "La casa" },
  { es: "el espejo", de: "der Spiegel", cat: "La casa" },
  { es: "la alfombra", de: "der Teppich", cat: "La casa" },
  { es: "la lámpara", de: "die Lampe", cat: "La casa" },                       // +
  { es: "la lámpara de pie", de: "die Stehlampe", cat: "La casa" },
  { es: "el cojín", de: "das Kissen", cat: "La casa" },
  { es: "la cortina", de: "der Vorhang", cat: "La casa" },                     // +
  { es: "el jarrón", de: "die Vase", cat: "La casa" },
  { es: "la vela", de: "die Kerze", cat: "La casa" },
  { es: "el perchero", de: "die Garderobe", cat: "La casa" },
  { es: "el despertador", de: "der Wecker", cat: "La casa" },
  // Geräte
  // Beide Wörter bedeuten exakt dasselbe — als EIN Eintrag mit „/", sonst waere
  // die Frage Richtung Deutsch->Spanisch nicht eindeutig loesbar. writeCorrect()
  // in app.js akzeptiert beim Schreiben ohnehin jede Variante vor/nach dem „/".
  { es: "la nevera / el frigorífico", de: "der Kühlschrank", cat: "La casa" },
  { es: "la lavadora", de: "die Waschmaschine", cat: "La casa" },
  { es: "el lavavajillas", de: "die Spülmaschine", cat: "La casa" },           // +
  { es: "el horno", de: "der Backofen", cat: "La casa" },
  { es: "la calefacción", de: "die Heizung", cat: "La casa" },
  { es: "el aire acondicionado", de: "die Klimaanlage", cat: "La casa" },
  { es: "la televisión", de: "der Fernseher", cat: "La casa" },                // +
  // Bad
  { es: "la ducha", de: "die Dusche", cat: "La casa" },
  { es: "la bañera", de: "die Badewanne", cat: "La casa" },
  { es: "el wáter", de: "die Toilette", cat: "La casa" },
  { es: "la toalla", de: "das Handtuch", cat: "La casa" },                     // +
  // Bau & Struktur
  { es: "la ventana", de: "das Fenster", cat: "La casa" },
  { es: "la puerta", de: "die Tür", cat: "La casa" },                          // +
  { es: "la pared", de: "die Wand", cat: "La casa" },                          // +
  { es: "el techo", de: "die Decke / das Dach", cat: "La casa" },              // +
  { es: "el suelo", de: "der Boden", cat: "La casa" },
  { es: "la escalera", de: "die Treppe", cat: "La casa" },                     // +
  { es: "el ascensor", de: "der Aufzug", cat: "La casa" },
  { es: "la persiana", de: "der Rollladen", cat: "La casa" },
  { es: "la llave", de: "der Schlüssel", cat: "La casa" },                     // +
  { es: "la luz", de: "das Licht", cat: "La casa" },
  // Wohnformen & Umfeld
  { es: "el piso", de: "die Wohnung", cat: "La casa" },
  { es: "el apartamento", de: "das Apartment", cat: "La casa" },
  { es: "el chalé", de: "das Einfamilienhaus / die Villa", cat: "La casa" },
  { es: "la casa adosada", de: "das Reihenhaus", cat: "La casa" },
  { es: "la casa de campo", de: "das Landhaus", cat: "La casa" },
  { es: "el edificio", de: "das Gebäude", cat: "La casa" },
  { es: "el barrio", de: "das Viertel", cat: "La casa" },
  { es: "el alquiler", de: "die Miete", cat: "La casa" },
  { es: "alquilar", de: "mieten / vermieten", cat: "La casa" },
  { es: "el vecino", de: "der Nachbar", cat: "La casa" },                      // +
  // Garten
  { es: "el jardín", de: "der Garten", cat: "La casa" },
  { es: "la piscina", de: "der Swimmingpool", cat: "La casa" },
  { es: "el césped", de: "der Rasen", cat: "La casa" },                        // +
  { es: "el árbol", de: "der Baum", cat: "La casa" },                          // +
  { es: "la flor", de: "die Blume", cat: "La casa" },                          // +
  { es: "la valla", de: "der Zaun", cat: "La casa" },                          // +
  { es: "la maceta", de: "der Blumentopf", cat: "La casa" },                   // +
  // Beschreibung
  { es: "amueblado/a", de: "möbliert", cat: "La casa" },
  { es: "sin amueblar", de: "unmöbliert", cat: "La casa" },
  { es: "luminoso/a", de: "hell (lichtdurchflutet)", cat: "La casa" },
  { es: "acogedor/a", de: "gemütlich", cat: "La casa" },
  { es: "amplio/a", de: "geräumig", cat: "La casa" },
  { es: "ruidoso/a", de: "laut", cat: "La casa" },
  { es: "tranquilo/a", de: "ruhig", cat: "La casa" },                          // +
  { es: "antiguo/a", de: "alt", cat: "La casa" },
  { es: "cómodo/a", de: "bequem", cat: "La casa" },
  { es: "las vistas", de: "die Aussicht", cat: "La casa" },

  // ============================================================
  //  Kurseinheiten 1, 2, 3, 5, 6, 8, 9, 10 — Aula Internacional Plus 2 (A2)
  //  Quelle: uni/spanisch/Vokabeln/Unit-*.md
  //  Kuratiert: konkrete Alltags- und Pruefungswoerter, ohne Randbegriffe.
  //  „// +" markiert Ergaenzungen, die NICHT im Kursglossar stehen.
  // ============================================================

  // --- Aprender idiomas (Unit 1: El español y tú) ---
  { es: "el idioma", de: "die Sprache", cat: "Aprender idiomas" },
  { es: "la lengua materna", de: "die Muttersprache", cat: "Aprender idiomas" },
  { es: "el español", de: "das Spanisch", cat: "Aprender idiomas" },
  { es: "el alemán", de: "das Deutsch", cat: "Aprender idiomas" },
  { es: "el inglés", de: "das Englisch", cat: "Aprender idiomas" },
  { es: "el francés", de: "das Französisch", cat: "Aprender idiomas" },
  { es: "el italiano", de: "das Italienisch", cat: "Aprender idiomas" },
  { es: "el país", de: "das Land (Staat)", cat: "Aprender idiomas" },
  { es: "el examen", de: "die Prüfung", cat: "Aprender idiomas" },
  { es: "la clase", de: "der Unterricht / die Klasse", cat: "Aprender idiomas" },
  { es: "estudiar", de: "studieren / lernen", cat: "Aprender idiomas" },
  { es: "aprender", de: "lernen", cat: "Aprender idiomas" },
  { es: "enseñar", de: "unterrichten / zeigen", cat: "Aprender idiomas" },
  { es: "entender", de: "verstehen", cat: "Aprender idiomas" },
  { es: "pronunciar", de: "aussprechen", cat: "Aprender idiomas" },
  { es: "traducir", de: "übersetzen", cat: "Aprender idiomas" },
  { es: "repetir", de: "wiederholen", cat: "Aprender idiomas" },
  { es: "recordar", de: "sich erinnern", cat: "Aprender idiomas" },
  { es: "memorizar", de: "auswendig lernen", cat: "Aprender idiomas" },
  { es: "escribir", de: "schreiben", cat: "Aprender idiomas" },
  { es: "leer", de: "lesen", cat: "Aprender idiomas" },
  { es: "escuchar", de: "zuhören", cat: "Aprender idiomas" },
  { es: "preguntar", de: "fragen", cat: "Aprender idiomas" },
  { es: "ayudar", de: "helfen", cat: "Aprender idiomas" },
  { es: "necesitar", de: "brauchen", cat: "Aprender idiomas" },
  { es: "intentar", de: "versuchen", cat: "Aprender idiomas" },
  { es: "usar", de: "benutzen", cat: "Aprender idiomas" },
  { es: "buscar", de: "suchen", cat: "Aprender idiomas" },
  { es: "el vocabulario", de: "der Wortschatz", cat: "Aprender idiomas" },
  { es: "la palabra", de: "das Wort", cat: "Aprender idiomas" },
  { es: "la frase", de: "der Satz", cat: "Aprender idiomas" },
  { es: "la regla", de: "die Regel", cat: "Aprender idiomas" },
  { es: "el ejercicio", de: "die Übung", cat: "Aprender idiomas" },
  { es: "el error", de: "der Fehler", cat: "Aprender idiomas" },          // +
  { es: "el texto", de: "der Text", cat: "Aprender idiomas" },
  { es: "el libro", de: "das Buch", cat: "Aprender idiomas" },
  { es: "el diccionario", de: "das Wörterbuch", cat: "Aprender idiomas" },
  { es: "el periódico", de: "die Zeitung", cat: "Aprender idiomas" },
  { es: "la revista", de: "die Zeitschrift", cat: "Aprender idiomas" },
  { es: "la novela", de: "der Roman", cat: "Aprender idiomas" },
  { es: "la pizarra", de: "die Tafel", cat: "Aprender idiomas" },
  { es: "el bolígrafo", de: "der Kugelschreiber", cat: "Aprender idiomas" },
  { es: "el lápiz", de: "der Bleistift", cat: "Aprender idiomas" },
  { es: "la hoja de papel", de: "das Blatt Papier", cat: "Aprender idiomas" },
  { es: "el móvil", de: "das Handy", cat: "Aprender idiomas" },
  { es: "difícil", de: "schwierig", cat: "Aprender idiomas" },
  { es: "fácil", de: "einfach", cat: "Aprender idiomas" },                // +
  { es: "importante", de: "wichtig", cat: "Aprender idiomas" },
  { es: "interesante", de: "interessant", cat: "Aprender idiomas" },
  { es: "nuevo/a", de: "neu", cat: "Aprender idiomas" },
  { es: "el tiempo libre", de: "die Freizeit", cat: "Aprender idiomas" },
  { es: "la gente", de: "die Leute", cat: "Aprender idiomas" },
  { es: "el consejo", de: "der Rat / der Tipp", cat: "Aprender idiomas" },
  { es: "la experiencia", de: "die Erfahrung", cat: "Aprender idiomas" },
  { es: "el extranjero", de: "das Ausland", cat: "Aprender idiomas" },
  { es: "viajar", de: "reisen", cat: "Aprender idiomas" },

  // --- Biografía (Unit 2: Una vida de película) ---
  { es: "nacer", de: "geboren werden", cat: "Biografía" },
  { es: "crecer", de: "aufwachsen", cat: "Biografía" },                   // +
  { es: "casarse", de: "heiraten", cat: "Biografía" },
  { es: "divorciarse", de: "sich scheiden lassen", cat: "Biografía" },
  { es: "separarse", de: "sich trennen", cat: "Biografía" },
  { es: "enamorarse", de: "sich verlieben", cat: "Biografía" },
  { es: "mudarse", de: "umziehen", cat: "Biografía" },
  { es: "jubilarse", de: "in Rente gehen", cat: "Biografía" },
  { es: "morir", de: "sterben", cat: "Biografía" },
  { es: "ganar", de: "gewinnen / verdienen", cat: "Biografía" },
  { es: "perder", de: "verlieren", cat: "Biografía" },
  { es: "conseguir", de: "erreichen / bekommen", cat: "Biografía" },
  { es: "empezar", de: "anfangen", cat: "Biografía" },
  { es: "terminar", de: "beenden", cat: "Biografía" },
  { es: "cambiar", de: "ändern / wechseln", cat: "Biografía" },
  { es: "dejar", de: "lassen / aufgeben", cat: "Biografía" },
  { es: "decidir", de: "entscheiden", cat: "Biografía" },
  { es: "recibir", de: "erhalten", cat: "Biografía" },
  { es: "crear", de: "schaffen", cat: "Biografía" },
  { es: "publicar", de: "veröffentlichen", cat: "Biografía" },
  { es: "visitar", de: "besuchen", cat: "Biografía" },
  { es: "regresar", de: "zurückkehren", cat: "Biografía" },
  { es: "la vida", de: "das Leben", cat: "Biografía" },
  { es: "la biografía", de: "der Lebenslauf / die Biografie", cat: "Biografía" },
  { es: "el apellido", de: "der Nachname", cat: "Biografía" },
  { es: "el nombre", de: "der Vorname / der Name", cat: "Biografía" },
  { es: "la fecha de nacimiento", de: "das Geburtsdatum", cat: "Biografía" },
  { es: "el lugar de nacimiento", de: "der Geburtsort", cat: "Biografía" },
  { es: "la carrera", de: "das Studium / die Laufbahn", cat: "Biografía" },
  { es: "el máster", de: "der Master", cat: "Biografía" },
  { es: "el conocimiento", de: "die Kenntnis", cat: "Biografía" },
  { es: "el logro", de: "die Leistung / der Erfolg", cat: "Biografía" },
  { es: "el éxito", de: "der Erfolg", cat: "Biografía" },
  { es: "el premio", de: "der Preis (Auszeichnung)", cat: "Biografía" },
  { es: "la empresa", de: "das Unternehmen", cat: "Biografía" },
  { es: "el dinero", de: "das Geld", cat: "Biografía" },
  { es: "el banco", de: "die Bank (Geld) / die Sitzbank", cat: "Biografía" },
  { es: "el hospital", de: "das Krankenhaus", cat: "Biografía" },
  { es: "la playa", de: "der Strand", cat: "Biografía" },
  { es: "la isla", de: "die Insel", cat: "Biografía" },
  { es: "el mar", de: "das Meer", cat: "Biografía" },
  { es: "el barco", de: "das Schiff", cat: "Biografía" },
  { es: "la mochila", de: "der Rucksack", cat: "Biografía" },
  { es: "la película", de: "der Film", cat: "Biografía" },
  { es: "el cine", de: "das Kino", cat: "Biografía" },
  { es: "la historia", de: "die Geschichte", cat: "Biografía" },
  { es: "el cuento", de: "die Erzählung / das Märchen", cat: "Biografía" },
  { es: "la cámara", de: "die Kamera", cat: "Biografía" },
  { es: "la foto", de: "das Foto", cat: "Biografía" },
  { es: "el deporte", de: "der Sport", cat: "Biografía" },
  { es: "el verano", de: "der Sommer", cat: "Biografía" },
  { es: "el campo", de: "das Feld / die ländliche Gegend", cat: "Biografía" },
  { es: "famoso/a", de: "berühmt", cat: "Biografía" },
  { es: "juntos/as", de: "zusammen", cat: "Biografía" },
  { es: "maravilloso/a", de: "wunderbar", cat: "Biografía" },
  { es: "casi", de: "fast", cat: "Biografía" },

  // --- Carácter (Unit 3: Yo soy así) ---
  { es: "el carácter", de: "der Charakter", cat: "Carácter" },
  { es: "la pareja", de: "der Partner / das Paar", cat: "Carácter" },
  { es: "el primo / la prima", de: "der Cousin / die Cousine", cat: "Carácter" },
  { es: "el tío / la tía", de: "der Onkel / die Tante", cat: "Carácter" },
  { es: "el sobrino / la sobrina", de: "der Neffe / die Nichte", cat: "Carácter" },
  { es: "el hermano / la hermana", de: "der Bruder / die Schwester", cat: "Carácter" },
  { es: "el hijo / la hija", de: "der Sohn / die Tochter", cat: "Carácter" },
  { es: "el abuelo / la abuela", de: "der Großvater / die Großmutter", cat: "Carácter" },
  { es: "el marido / el esposo", de: "der Ehemann", cat: "Carácter" },
  { es: "la esposa", de: "die Ehefrau", cat: "Carácter" },
  { es: "el novio / la novia", de: "der feste Freund / die feste Freundin", cat: "Carácter" },
  { es: "el jefe / la jefa", de: "der Chef / die Chefin", cat: "Carácter" },
  { es: "el estado civil", de: "der Familienstand", cat: "Carácter" },
  { es: "soltero/a", de: "ledig", cat: "Carácter" },
  { es: "casado/a", de: "verheiratet", cat: "Carácter" },
  { es: "divorciado/a", de: "geschieden", cat: "Carácter" },
  { es: "viudo/a", de: "verwitwet", cat: "Carácter" },
  { es: "la edad", de: "das Alter", cat: "Carácter" },
  { es: "joven", de: "jung", cat: "Carácter" },
  { es: "mayor", de: "älter / groß (Alter)", cat: "Carácter" },            // +
  { es: "alto/a", de: "groß (Körpergröße)", cat: "Carácter" },
  { es: "bajo/a", de: "klein (Körpergröße)", cat: "Carácter" },            // +
  { es: "delgado/a", de: "schlank", cat: "Carácter" },
  { es: "gordo/a", de: "dick", cat: "Carácter" },
  { es: "guapo/a", de: "hübsch / gutaussehend", cat: "Carácter" },
  { es: "feo/a", de: "hässlich", cat: "Carácter" },
  { es: "moreno/a", de: "dunkelhaarig", cat: "Carácter" },
  { es: "rubio/a", de: "blond", cat: "Carácter" },
  { es: "pelirrojo/a", de: "rothaarig", cat: "Carácter" },
  { es: "castaño/a", de: "braunhaarig", cat: "Carácter" },
  { es: "canoso/a", de: "grauhaarig", cat: "Carácter" },
  { es: "calvo/a", de: "glatzköpfig", cat: "Carácter" },
  { es: "liso/a", de: "glatt (Haar)", cat: "Carácter" },
  { es: "rizado/a", de: "lockig", cat: "Carácter" },
  { es: "largo/a", de: "lang", cat: "Carácter" },
  { es: "corto/a", de: "kurz", cat: "Carácter" },
  { es: "la barba", de: "der Bart", cat: "Carácter" },
  { es: "el bigote", de: "der Schnurrbart", cat: "Carácter" },
  { es: "las gafas", de: "die Brille", cat: "Carácter" },
  { es: "las gafas de sol", de: "die Sonnenbrille", cat: "Carácter" },
  { es: "la sonrisa", de: "das Lächeln", cat: "Carácter" },
  { es: "simpático/a", de: "sympathisch", cat: "Carácter" },
  { es: "antipático/a", de: "unsympathisch", cat: "Carácter" },
  { es: "alegre", de: "fröhlich", cat: "Carácter" },
  { es: "optimista", de: "optimistisch", cat: "Carácter" },
  { es: "extrovertido/a", de: "extrovertiert", cat: "Carácter" },
  { es: "tímido/a", de: "schüchtern", cat: "Carácter" },                  // +
  { es: "inteligente", de: "intelligent", cat: "Carácter" },
  { es: "trabajador/a", de: "fleißig", cat: "Carácter" },
  { es: "divertido/a", de: "lustig", cat: "Carácter" },
  { es: "aburrido/a", de: "langweilig", cat: "Carácter" },
  { es: "cariñoso/a", de: "liebevoll", cat: "Carácter" },
  { es: "activo/a", de: "aktiv", cat: "Carácter" },
  { es: "deportista", de: "sportlich", cat: "Carácter" },
  { es: "llevarse bien", de: "sich gut verstehen", cat: "Carácter" },
  { es: "caer bien", de: "sympathisch sein", cat: "Carácter" },
  { es: "parecerse", de: "sich ähneln", cat: "Carácter" },
  { es: "la ropa", de: "die Kleidung", cat: "Carácter" },
  { es: "el vestido", de: "das Kleid", cat: "Carácter" },
  { es: "la camisa", de: "das Hemd", cat: "Carácter" },
  { es: "la camiseta", de: "das T-Shirt", cat: "Carácter" },
  { es: "los pantalones", de: "die Hose", cat: "Carácter" },
  { es: "los vaqueros", de: "die Jeans", cat: "Carácter" },
  { es: "la chaqueta", de: "die Jacke", cat: "Carácter" },
  { es: "el traje", de: "der Anzug", cat: "Carácter" },
  { es: "el bolso", de: "die Handtasche", cat: "Carácter" },
  { es: "el coche", de: "das Auto", cat: "Carácter" },
  { es: "blanco/a", de: "weiß", cat: "Carácter" },                        // +
  { es: "negro/a", de: "schwarz", cat: "Carácter" },
  { es: "rojo/a", de: "rot", cat: "Carácter" },
  { es: "azul", de: "blau", cat: "Carácter" },
  { es: "verde", de: "grün", cat: "Carácter" },
  { es: "amarillo/a", de: "gelb", cat: "Carácter" },                      // +
  { es: "gris", de: "grau", cat: "Carácter" },
  { es: "marrón", de: "braun", cat: "Carácter" },

  // --- Saludos y estado (Unit 5: ¿Cómo va todo?) ---
  { es: "saludar", de: "grüßen", cat: "Saludos y estado" },
  { es: "¿qué tal?", de: "wie geht's?", cat: "Saludos y estado" },
  { es: "¿cómo estás?", de: "wie geht es dir?", cat: "Saludos y estado" },
  { es: "mucho gusto", de: "sehr erfreut", cat: "Saludos y estado" },
  { es: "encantado/a", de: "freut mich (beim Kennenlernen)", cat: "Saludos y estado" },
  { es: "de nada", de: "gern geschehen", cat: "Saludos y estado" },
  { es: "dar las gracias", de: "sich bedanken", cat: "Saludos y estado" },
  { es: "dar un beso", de: "einen Kuss geben", cat: "Saludos y estado" },
  { es: "dar un abrazo", de: "umarmen", cat: "Saludos y estado" },
  { es: "dar la mano", de: "die Hand geben", cat: "Saludos y estado" },
  { es: "disculparse", de: "sich entschuldigen", cat: "Saludos y estado" },
  { es: "pedir un favor", de: "um einen Gefallen bitten", cat: "Saludos y estado" },
  { es: "pedir permiso", de: "um Erlaubnis bitten", cat: "Saludos y estado" },
  { es: "prestar", de: "leihen (geben)", cat: "Saludos y estado" },
  { es: "devolver", de: "zurückgeben", cat: "Saludos y estado" },
  { es: "dar", de: "geben", cat: "Saludos y estado" },
  { es: "traer", de: "bringen", cat: "Saludos y estado" },
  { es: "comprar", de: "kaufen", cat: "Saludos y estado" },
  { es: "pagar", de: "bezahlen", cat: "Saludos y estado" },
  { es: "abrir", de: "öffnen", cat: "Saludos y estado" },
  { es: "cerrar", de: "schließen", cat: "Saludos y estado" },
  { es: "entrar", de: "hineingehen", cat: "Saludos y estado" },
  { es: "caminar", de: "gehen / laufen", cat: "Saludos y estado" },
  { es: "beber", de: "trinken", cat: "Saludos y estado" },
  { es: "oír", de: "hören", cat: "Saludos y estado" },
  { es: "sentir", de: "fühlen", cat: "Saludos y estado" },
  { es: "seguir", de: "folgen / weitermachen", cat: "Saludos y estado" },
  { es: "mentir", de: "lügen", cat: "Saludos y estado" },
  { es: "limpiar", de: "putzen", cat: "Saludos y estado" },
  { es: "ducharse", de: "duschen", cat: "Saludos y estado" },
  { es: "quedar", de: "sich verabreden", cat: "Saludos y estado" },
  { es: "quedarse", de: "bleiben", cat: "Saludos y estado" },
  { es: "responder", de: "antworten", cat: "Saludos y estado" },
  { es: "llegar tarde", de: "zu spät kommen", cat: "Saludos y estado" },
  { es: "tener prisa", de: "es eilig haben", cat: "Saludos y estado" },
  { es: "tener sed", de: "Durst haben", cat: "Saludos y estado" },
  { es: "tener hambre", de: "Hunger haben", cat: "Saludos y estado" },    // +
  { es: "tener miedo", de: "Angst haben", cat: "Saludos y estado" },
  { es: "el regalo", de: "das Geschenk", cat: "Saludos y estado" },
  { es: "el teléfono", de: "das Telefon", cat: "Saludos y estado" },
  { es: "la llamada", de: "der Anruf", cat: "Saludos y estado" },
  { es: "el reloj", de: "die Uhr", cat: "Saludos y estado" },
  { es: "la bolsa", de: "die Tüte / die Tasche", cat: "Saludos y estado" },
  { es: "la maleta", de: "der Koffer", cat: "Saludos y estado" },
  { es: "el paquete", de: "das Paket", cat: "Saludos y estado" },
  { es: "la cuenta", de: "die Rechnung", cat: "Saludos y estado" },
  { es: "la tarjeta de crédito", de: "die Kreditkarte", cat: "Saludos y estado" },
  { es: "el supermercado", de: "der Supermarkt", cat: "Saludos y estado" },
  { es: "la panadería", de: "die Bäckerei", cat: "Saludos y estado" },
  { es: "la cafetería", de: "das Café", cat: "Saludos y estado" },
  { es: "el museo", de: "das Museum", cat: "Saludos y estado" },
  { es: "el autobús", de: "der Bus", cat: "Saludos y estado" },
  { es: "el problema", de: "das Problem", cat: "Saludos y estado" },
  { es: "el ruido", de: "der Lärm", cat: "Saludos y estado" },
  { es: "amable", de: "freundlich", cat: "Saludos y estado" },
  { es: "agradable", de: "angenehm", cat: "Saludos y estado" },
  { es: "malo/a", de: "schlecht / böse", cat: "Saludos y estado" },
  { es: "sucio/a", de: "schmutzig", cat: "Saludos y estado" },
  { es: "limpio/a", de: "sauber", cat: "Saludos y estado" },              // +
  { es: "caliente", de: "heiß", cat: "Saludos y estado" },
  { es: "frío/a", de: "kalt", cat: "Saludos y estado" },                  // +
  { es: "útil", de: "nützlich", cat: "Saludos y estado" },
  { es: "increíble", de: "unglaublich", cat: "Saludos y estado" },
  { es: "sincero/a", de: "aufrichtig", cat: "Saludos y estado" },

  // --- Ocio (Unit 6: Guía del ocio) ---
  { es: "el ocio", de: "die Freizeit / die Muße", cat: "Ocio" },
  { es: "disfrutar", de: "genießen", cat: "Ocio" },
  { es: "relajarse", de: "sich entspannen", cat: "Ocio" },
  { es: "el teatro", de: "das Theater", cat: "Ocio" },
  { es: "el concierto", de: "das Konzert", cat: "Ocio" },
  { es: "la exposición", de: "die Ausstellung", cat: "Ocio" },
  { es: "el festival", de: "das Festival", cat: "Ocio" },
  { es: "la entrada", de: "die Eintrittskarte", cat: "Ocio" },
  { es: "el arte", de: "die Kunst", cat: "Ocio" },
  { es: "la música", de: "die Musik", cat: "Ocio" },
  { es: "la canción", de: "das Lied", cat: "Ocio" },
  { es: "el juego", de: "das Spiel", cat: "Ocio" },
  { es: "el juguete", de: "das Spielzeug", cat: "Ocio" },
  { es: "la discoteca", de: "die Diskothek", cat: "Ocio" },
  { es: "la cerveza", de: "das Bier", cat: "Ocio" },
  { es: "el vino", de: "der Wein", cat: "Ocio" },
  { es: "el sabor", de: "der Geschmack", cat: "Ocio" },
  { es: "el ingrediente", de: "die Zutat", cat: "Ocio" },
  { es: "el ambiente", de: "die Atmosphäre", cat: "Ocio" },
  { es: "el sitio", de: "der Ort / die Stelle", cat: "Ocio" },
  { es: "el local", de: "das Lokal", cat: "Ocio" },
  { es: "la oficina", de: "das Büro", cat: "Ocio" },
  { es: "la página web", de: "die Webseite", cat: "Ocio" },
  { es: "el correo electrónico", de: "die E-Mail", cat: "Ocio" },
  { es: "la carta", de: "der Brief / die Speisekarte", cat: "Ocio" },
  { es: "la bicicleta", de: "das Fahrrad", cat: "Ocio" },
  { es: "la montaña", de: "der Berg", cat: "Ocio" },
  { es: "el paseo", de: "der Spaziergang", cat: "Ocio" },
  { es: "el partido", de: "das Match / die Partie", cat: "Ocio" },
  { es: "correr", de: "rennen / laufen", cat: "Ocio" },
  { es: "nadar", de: "schwimmen", cat: "Ocio" },
  { es: "bailar", de: "tanzen", cat: "Ocio" },                            // +
  { es: "cantar", de: "singen", cat: "Ocio" },                            // +
  { es: "dibujar", de: "zeichnen", cat: "Ocio" },
  { es: "patinar", de: "Rollschuh laufen", cat: "Ocio" },
  { es: "hacer senderismo", de: "wandern", cat: "Ocio" },
  { es: "montar a caballo", de: "reiten", cat: "Ocio" },
  { es: "ir de compras", de: "einkaufen gehen", cat: "Ocio" },
  { es: "ir al gimnasio", de: "ins Fitnessstudio gehen", cat: "Ocio" },
  { es: "ir en bici", de: "Fahrrad fahren", cat: "Ocio" },
  { es: "tocar un instrumento", de: "ein Instrument spielen", cat: "Ocio" },
  { es: "apuntarse", de: "sich anmelden", cat: "Ocio" },
  { es: "ofrecer", de: "anbieten", cat: "Ocio" },
  { es: "consultar", de: "nachschlagen / sich erkundigen", cat: "Ocio" },
  { es: "valorar", de: "bewerten", cat: "Ocio" },
  { es: "al aire libre", de: "im Freien", cat: "Ocio" },
  { es: "a menudo", de: "oft", cat: "Ocio" },
  { es: "esta noche", de: "heute Abend", cat: "Ocio" },
  { es: "pasado mañana", de: "übermorgen", cat: "Ocio" },
  { es: "el mes que viene", de: "nächsten Monat", cat: "Ocio" },
  { es: "el futuro", de: "die Zukunft", cat: "Ocio" },
  { es: "bonito/a", de: "schön / hübsch", cat: "Ocio" },
  { es: "delicioso/a", de: "köstlich", cat: "Ocio" },
  { es: "rico/a", de: "lecker / reich", cat: "Ocio" },
  { es: "sencillo/a", de: "einfach / schlicht", cat: "Ocio" },
  { es: "rápido/a", de: "schnell", cat: "Ocio" },
  { es: "lento/a", de: "langsam", cat: "Ocio" },
  { es: "económico/a", de: "günstig", cat: "Ocio" },
  { es: "estupendo/a", de: "großartig", cat: "Ocio" },
  { es: "único/a", de: "einzigartig", cat: "Ocio" },

  // --- Salud (Unit 8: Estamos muy bien) ---
  { es: "la salud", de: "die Gesundheit", cat: "Salud" },
  { es: "el dolor", de: "der Schmerz", cat: "Salud" },
  { es: "doler", de: "wehtun", cat: "Salud" },
  { es: "el dolor de cabeza", de: "die Kopfschmerzen", cat: "Salud" },
  { es: "el dolor de garganta", de: "die Halsschmerzen", cat: "Salud" },
  { es: "la tos", de: "der Husten", cat: "Salud" },
  { es: "el resfriado", de: "die Erkältung", cat: "Salud" },
  { es: "la gripe", de: "die Grippe", cat: "Salud" },
  { es: "la fiebre", de: "das Fieber", cat: "Salud" },
  { es: "las náuseas", de: "die Übelkeit", cat: "Salud" },
  { es: "la diarrea", de: "der Durchfall", cat: "Salud" },
  { es: "la herida", de: "die Wunde", cat: "Salud" },
  { es: "la enfermedad", de: "die Krankheit", cat: "Salud" },
  { es: "enfermo/a", de: "krank", cat: "Salud" },
  { es: "sano/a", de: "gesund", cat: "Salud" },                           // +
  { es: "mareado/a", de: "schwindelig", cat: "Salud" },
  { es: "pálido/a", de: "blass", cat: "Salud" },
  { es: "cansado/a", de: "müde", cat: "Salud" },
  { es: "nervioso/a", de: "nervös", cat: "Salud" },
  { es: "preocupado/a", de: "besorgt", cat: "Salud" },
  { es: "estresado/a", de: "gestresst", cat: "Salud" },
  { es: "contento/a", de: "zufrieden", cat: "Salud" },
  { es: "enfadado/a", de: "verärgert", cat: "Salud" },
  { es: "sorprendido/a", de: "überrascht", cat: "Salud" },
  { es: "impaciente", de: "ungeduldig", cat: "Salud" },
  { es: "el estado de ánimo", de: "die Stimmung", cat: "Salud" },
  { es: "el estrés", de: "der Stress", cat: "Salud" },
  { es: "el insomnio", de: "die Schlaflosigkeit", cat: "Salud" },
  { es: "la depresión", de: "die Depression", cat: "Salud" },
  { es: "el médico / la médica", de: "der Arzt / die Ärztin", cat: "Salud" },
  { es: "el dentista / la dentista", de: "der Zahnarzt / die Zahnärztin", cat: "Salud" },
  { es: "la muela", de: "der Backenzahn", cat: "Salud" },
  { es: "el oído", de: "das Ohr (innen) / das Gehör", cat: "Salud" },
  { es: "el vientre", de: "der Unterleib", cat: "Salud" },
  { es: "el cabello", de: "das Haar (gehoben)", cat: "Salud" },
  { es: "el jabón", de: "die Seife", cat: "Salud" },
  { es: "el champú", de: "das Shampoo", cat: "Salud" },
  { es: "la mascarilla", de: "die Maske", cat: "Salud" },
  { es: "el protector solar", de: "der Sonnenschutz", cat: "Salud" },
  { es: "el guante", de: "der Handschuh", cat: "Salud" },
  { es: "el gorro", de: "die Mütze", cat: "Salud" },
  { es: "la medicina", de: "die Medizin", cat: "Salud" },
  { es: "la farmacia", de: "die Apotheke", cat: "Salud" },
  { es: "cuidarse", de: "auf sich achten", cat: "Salud" },
  { es: "evitar", de: "vermeiden", cat: "Salud" },
  { es: "proteger", de: "schützen", cat: "Salud" },
  { es: "prevenir", de: "vorbeugen", cat: "Salud" },
  { es: "respirar", de: "atmen", cat: "Salud" },
  { es: "dormir", de: "schlafen", cat: "Salud" },
  { es: "acostarse", de: "sich hinlegen", cat: "Salud" },
  { es: "caerse", de: "hinfallen", cat: "Salud" },
  { es: "fumar", de: "rauchen", cat: "Salud" },
  { es: "adelgazar", de: "abnehmen", cat: "Salud" },
  { es: "estar en forma", de: "fit sein", cat: "Salud" },
  { es: "hacer ejercicio", de: "sich bewegen / trainieren", cat: "Salud" },
  { es: "hacer deporte", de: "Sport treiben", cat: "Salud" },
  { es: "la dieta equilibrada", de: "die ausgewogene Ernährung", cat: "Salud" },
  { es: "el invierno", de: "der Winter", cat: "Salud" },
  { es: "suave", de: "sanft / mild", cat: "Salud" },
  { es: "despacio", de: "gemächlich / in Ruhe", cat: "Salud" },

  // --- Antes y ahora (Unit 9) ---
  { es: "antes", de: "früher / vorher", cat: "Antes y ahora" },
  { es: "entonces", de: "damals / dann", cat: "Antes y ahora" },
  { es: "todavía", de: "noch", cat: "Antes y ahora" },
  { es: "ya no", de: "nicht mehr", cat: "Antes y ahora" },
  { es: "hoy en día", de: "heutzutage", cat: "Antes y ahora" },
  { es: "la época", de: "die Epoche / die Zeit", cat: "Antes y ahora" },
  { es: "el siglo", de: "das Jahrhundert", cat: "Antes y ahora" },        // +
  { es: "la infancia", de: "die Kindheit", cat: "Antes y ahora" },
  { es: "la juventud", de: "die Jugend", cat: "Antes y ahora" },
  { es: "la adolescencia", de: "die Pubertät", cat: "Antes y ahora" },
  { es: "la vejez", de: "das hohe Alter", cat: "Antes y ahora" },
  { es: "el bebé", de: "das Baby", cat: "Antes y ahora" },
  { es: "adulto/a", de: "erwachsen", cat: "Antes y ahora" },
  { es: "la persona mayor", de: "der ältere Mensch", cat: "Antes y ahora" },
  { es: "la sociedad", de: "die Gesellschaft", cat: "Antes y ahora" },
  { es: "el gobierno", de: "die Regierung", cat: "Antes y ahora" },
  { es: "la ley", de: "das Gesetz", cat: "Antes y ahora" },               // +
  { es: "el derecho", de: "das Recht", cat: "Antes y ahora" },
  { es: "la libertad", de: "die Freiheit", cat: "Antes y ahora" },
  { es: "la igualdad", de: "die Gleichheit", cat: "Antes y ahora" },
  { es: "la educación", de: "die Bildung / die Erziehung", cat: "Antes y ahora" },
  { es: "la democracia", de: "die Demokratie", cat: "Antes y ahora" },
  { es: "la dictadura", de: "die Diktatur", cat: "Antes y ahora" },
  { es: "la frontera", de: "die Grenze", cat: "Antes y ahora" },
  { es: "la nacionalidad", de: "die Staatsangehörigkeit", cat: "Antes y ahora" },
  { es: "la población", de: "die Bevölkerung", cat: "Antes y ahora" },
  { es: "prohibido/a", de: "verboten", cat: "Antes y ahora" },
  { es: "ilegal", de: "illegal", cat: "Antes y ahora" },
  { es: "existir", de: "existieren", cat: "Antes y ahora" },
  { es: "producir", de: "herstellen", cat: "Antes y ahora" },
  { es: "cultivar", de: "anbauen", cat: "Antes y ahora" },
  { es: "atraer", de: "anziehen", cat: "Antes y ahora" },
  { es: "subir", de: "steigen / hinaufgehen", cat: "Antes y ahora" },
  { es: "bañarse", de: "baden", cat: "Antes y ahora" },
  { es: "tomar el sol", de: "sonnenbaden", cat: "Antes y ahora" },
  { es: "estar de moda", de: "in Mode sein", cat: "Antes y ahora" },
  { es: "el bañador", de: "die Badehose / der Badeanzug", cat: "Antes y ahora" },
  { es: "el aeropuerto", de: "der Flughafen", cat: "Antes y ahora" },
  { es: "el avión", de: "das Flugzeug", cat: "Antes y ahora" },
  { es: "el medio de transporte", de: "das Verkehrsmittel", cat: "Antes y ahora" },
  { es: "la tecnología", de: "die Technik", cat: "Antes y ahora" },
  { es: "la electricidad", de: "der Strom", cat: "Antes y ahora" },
  { es: "el invento", de: "die Erfindung", cat: "Antes y ahora" },
  { es: "la rueda", de: "das Rad", cat: "Antes y ahora" },
  { es: "la vacuna", de: "die Impfung", cat: "Antes y ahora" },
  { es: "el fuego", de: "das Feuer", cat: "Antes y ahora" },
  { es: "la naturaleza", de: "die Natur", cat: "Antes y ahora" },
  { es: "el medio ambiente", de: "die Umwelt", cat: "Antes y ahora" },
  { es: "la economía", de: "die Wirtschaft", cat: "Antes y ahora" },
  { es: "el comercio", de: "der Handel", cat: "Antes y ahora" },
  { es: "el oro", de: "das Gold", cat: "Antes y ahora" },
  { es: "la calidad", de: "die Qualität", cat: "Antes y ahora" },
  { es: "el respeto", de: "der Respekt", cat: "Antes y ahora" },
  { es: "la muerte", de: "der Tod", cat: "Antes y ahora" },
  { es: "duro/a", de: "hart", cat: "Antes y ahora" },
  { es: "precioso/a", de: "wunderschön", cat: "Antes y ahora" },

  // --- Fiestas (Unit 10: Momentos especiales) ---
  { es: "el cumpleaños", de: "der Geburtstag", cat: "Fiestas" },
  { es: "la fiesta", de: "das Fest / die Party", cat: "Fiestas" },
  { es: "la fiesta sorpresa", de: "die Überraschungsparty", cat: "Fiestas" },
  { es: "la sorpresa", de: "die Überraschung", cat: "Fiestas" },
  { es: "invitar", de: "einladen", cat: "Fiestas" },
  { es: "celebrar", de: "feiern", cat: "Fiestas" },                       // +
  { es: "merendar", de: "einen Nachmittagssnack essen", cat: "Fiestas" },
  { es: "la anécdota", de: "die Anekdote", cat: "Fiestas" },
  { es: "el viaje", de: "die Reise", cat: "Fiestas" },
  { es: "la llegada", de: "die Ankunft", cat: "Fiestas" },
  { es: "la estación de tren", de: "der Bahnhof", cat: "Fiestas" },
  { es: "el billete", de: "die Fahrkarte", cat: "Fiestas" },
  { es: "el taxi", de: "das Taxi", cat: "Fiestas" },
  { es: "la gasolina", de: "das Benzin", cat: "Fiestas" },
  { es: "el equipo", de: "die Ausrüstung / die Mannschaft", cat: "Fiestas" },
  { es: "la policía", de: "die Polizei", cat: "Fiestas" },
  { es: "el guardia", de: "der Wachmann", cat: "Fiestas" },
  { es: "el bombero / la bombera", de: "der Feuerwehrmann / die Feuerwehrfrau", cat: "Fiestas" },
  { es: "el incendio", de: "der Brand", cat: "Fiestas" },
  { es: "el accidente", de: "der Unfall", cat: "Fiestas" },
  { es: "la catástrofe natural", de: "die Naturkatastrophe", cat: "Fiestas" },
  { es: "el huracán", de: "der Hurrikan", cat: "Fiestas" },
  { es: "el terremoto", de: "das Erdbeben", cat: "Fiestas" },
  { es: "la guerra", de: "der Krieg", cat: "Fiestas" },
  { es: "la crisis", de: "die Krise", cat: "Fiestas" },
  { es: "el conflicto", de: "der Konflikt", cat: "Fiestas" },
  { es: "la revolución", de: "die Revolution", cat: "Fiestas" },
  { es: "el descubrimiento", de: "die Entdeckung", cat: "Fiestas" },
  { es: "la consecuencia", de: "die Folge", cat: "Fiestas" },
  { es: "el hecho", de: "die Tatsache", cat: "Fiestas" },
  { es: "el caso", de: "der Fall", cat: "Fiestas" },
  { es: "la explicación", de: "die Erklärung", cat: "Fiestas" },
  { es: "la elección", de: "die Wahl", cat: "Fiestas" },
  { es: "llorar", de: "weinen", cat: "Fiestas" },
  { es: "reír", de: "lachen", cat: "Fiestas" },
  { es: "enfadarse", de: "sich ärgern", cat: "Fiestas" },
  { es: "emocionarse", de: "gerührt sein", cat: "Fiestas" },
  { es: "ponerse nervioso/a", de: "nervös werden", cat: "Fiestas" },
  { es: "darse cuenta", de: "bemerken", cat: "Fiestas" },
  { es: "equivocarse", de: "sich irren", cat: "Fiestas" },
  { es: "enterarse", de: "erfahren", cat: "Fiestas" },
  { es: "ocurrir", de: "geschehen", cat: "Fiestas" },
  { es: "tener lugar", de: "stattfinden", cat: "Fiestas" },
  { es: "romper", de: "zerbrechen", cat: "Fiestas" },
  { es: "apagar", de: "ausschalten / löschen", cat: "Fiestas" },
  { es: "encender", de: "anschalten / anzünden", cat: "Fiestas" },
  { es: "acercarse", de: "sich nähern", cat: "Fiestas" },
  { es: "desaparecer", de: "verschwinden", cat: "Fiestas" },
  { es: "huir", de: "fliehen", cat: "Fiestas" },
  { es: "llover", de: "regnen", cat: "Fiestas" },
  { es: "controlar", de: "kontrollieren", cat: "Fiestas" },
  { es: "tardar", de: "dauern / brauchen (Zeit)", cat: "Fiestas" },
  { es: "la vergüenza", de: "die Scham", cat: "Fiestas" },
  { es: "el calor", de: "die Hitze", cat: "Fiestas" },
  { es: "de repente", de: "plötzlich", cat: "Fiestas" },
  { es: "sin duda", de: "ohne Zweifel", cat: "Fiestas" },
  { es: "emocionante", de: "aufregend", cat: "Fiestas" },
  { es: "estresante", de: "stressig", cat: "Fiestas" },

  // --- Ubicación (Ortsangaben) --- Quelle: uni/spanisch/Grammatik/Ortsvokabeln + Ortsadverbien
  { es: "encima de / sobre", de: "auf", cat: "Ubicación" },
  { es: "debajo de", de: "unter", cat: "Ubicación" },
  { es: "al lado de / junto a", de: "neben", cat: "Ubicación" },
  { es: "a la izquierda de", de: "links von", cat: "Ubicación" },
  { es: "a la derecha de", de: "rechts von", cat: "Ubicación" },
  { es: "delante de", de: "vor", cat: "Ubicación" },
  { es: "detrás de", de: "hinter", cat: "Ubicación" },
  { es: "entre", de: "zwischen", cat: "Ubicación" },
  { es: "dentro de", de: "in / innerhalb", cat: "Ubicación" },
  { es: "cerca de", de: "nah bei / in der Nähe von", cat: "Ubicación" },
  { es: "lejos de", de: "weit von", cat: "Ubicación" },
  { es: "aquí", de: "hier (beim Sprecher)", cat: "Ubicación" },
  { es: "ahí", de: "da / dort (beim Hörer)", cat: "Ubicación" },
  { es: "allí", de: "dort (konkreter Ort)", cat: "Ubicación" },
  { es: "allá", de: "dort drüben (Richtung)", cat: "Ubicación" },

  // --- El cuerpo (Körper & Körperteile) ---
  { es: "la cabeza", de: "der Kopf", cat: "El cuerpo" },
  { es: "la cara", de: "das Gesicht", cat: "El cuerpo" },
  { es: "el pelo", de: "das Haar / die Haare", cat: "El cuerpo" },
  { es: "la frente", de: "die Stirn", cat: "El cuerpo" },
  { es: "el ojo", de: "das Auge", cat: "El cuerpo" },
  { es: "la ceja", de: "die Augenbraue", cat: "El cuerpo" },
  { es: "la pestaña", de: "die Wimper", cat: "El cuerpo" },
  { es: "la oreja", de: "das Ohr", cat: "El cuerpo" },
  { es: "la nariz", de: "die Nase", cat: "El cuerpo" },
  { es: "la mejilla", de: "die Wange", cat: "El cuerpo" },
  { es: "la boca", de: "der Mund", cat: "El cuerpo" },
  { es: "el labio", de: "die Lippe", cat: "El cuerpo" },
  { es: "el diente", de: "der Zahn", cat: "El cuerpo" },
  { es: "la lengua", de: "die Zunge", cat: "El cuerpo" },
  { es: "la barbilla", de: "das Kinn", cat: "El cuerpo" },
  { es: "el cuello", de: "der Hals", cat: "El cuerpo" },
  { es: "la garganta", de: "der Hals / Rachen (innen)", cat: "El cuerpo" },
  { es: "el hombro", de: "die Schulter", cat: "El cuerpo" },
  { es: "el brazo", de: "der Arm", cat: "El cuerpo" },
  { es: "el codo", de: "der Ellbogen", cat: "El cuerpo" },
  { es: "la muñeca", de: "das Handgelenk", cat: "El cuerpo" },
  { es: "la mano", de: "die Hand", cat: "El cuerpo" },
  { es: "el dedo", de: "der Finger", cat: "El cuerpo" },
  { es: "la uña", de: "der Fingernagel", cat: "El cuerpo" },
  { es: "el pecho", de: "die Brust", cat: "El cuerpo" },
  { es: "la espalda", de: "der Rücken", cat: "El cuerpo" },
  { es: "el estómago", de: "der Magen", cat: "El cuerpo" },
  { es: "la barriga", de: "der Bauch", cat: "El cuerpo" },
  { es: "la cadera", de: "die Hüfte", cat: "El cuerpo" },
  { es: "la pierna", de: "das Bein", cat: "El cuerpo" },
  { es: "la rodilla", de: "das Knie", cat: "El cuerpo" },
  { es: "el tobillo", de: "der Knöchel", cat: "El cuerpo" },
  { es: "el pie", de: "der Fuß", cat: "El cuerpo" },
  { es: "el dedo del pie", de: "der Zeh", cat: "El cuerpo" },
  { es: "el corazón", de: "das Herz", cat: "El cuerpo" },
  { es: "el hueso", de: "der Knochen", cat: "El cuerpo" },
  // In Unit 4 (Möbel/Materialien) steht „la piel" für Leder — daher beide Bedeutungen
  // in EINEM Eintrag statt eines zweiten mit gleichem Schlüssel.
  { es: "la piel", de: "die Haut / das Leder", cat: "El cuerpo" },
  { es: "la sangre", de: "das Blut", cat: "El cuerpo" },
];
